### ISSUE TITLE
Versionable Legal Form 

### ISSUE THREAD

**Issue by burton1982** [rafalp/Misago#1001]
As talked with @rafalp :

> We will record time and contents of agreement when user has given it, together with copying that agreement in shape it was when user has given it, to database.
> We will also provide an option between agrement's level of importance: ergo just notify user, or require user to agree or remove their data.

**Comment by burton1982** [comment]
So I was looking where to implement this stuff. So just to make sure:
 I did a grep for ′privacy_policy′ and it seems that this is just a parameter which gets overriden somewhere. Is that right?

I would start by creating those models which are needed and place them in ′misago/legal′. 
I am just  wondering because there is nothing.

**Comment by rafalp** [comment]
You will need to add three models to `misago/legal`:

- LegalAgreement
- LegalAgreementVersion (will record versions of agreements as accepted by user)
- UserAgreement (will record agreement given by user)

But there are already challenges here:

- ToS and Privacy Policy are single agreement on registration.

Also keep on mind that Misago is not just Django app. There's Django backend writen with REST Framework and React.js application talking to it that clients see.

**Comment by burton1982** [comment]
Thanks! Yeah, I have fear about the this React.js stuff but as far as I understand most parts can be written without that beacause die Admincp does not rely on that.  So everything should be setup there, with a kind of history. Later, if the User wants to use the Forum, he will be forced to `Accept` the terms. I think this and the Conditional Logic must be written in `Gulp.js`right?

**Comment by rafalp** [comment]
the forms to accept agreements will need to be done in React.js, but if we keep this PR focused to admin and backend, I may then update frontend on my own later.

**Comment by rafalp** [comment]
Fixed in #1047
