### ISSUE TITLE
Error: Minified React error #105; 

### ISSUE THREAD

**Issue by khrizo** [rafalp/Misago#1015]
`Error: Minified React error #105;  visit http://facebook.github.io/react/docs/error-decoder.html?invariant=105&args[]=i for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`

started with 0.17 installed, worked fine then upgraded to 0.18 getting the error in vendor.js

Sorry, I forgot to mention this happens when you click on sign in or register.

**Comment by isgk** [comment]
I'm getting the same error.

**Comment by rafalp** [comment]
Thanks for report

> Sorry, I forgot to mention this happens when you click on sign in or register.

Yes, 0.18 includes changes on sign in and register forms to display "log in with social site" buttons, but that change was additive and shouldn't cause errors for those without any social login features enables.

Thanks, I'll give this a look today.

**Comment by Sebschock** [comment]
Im also getting the error with a fresh install following https://misago.gitbook.io/docs/setup-and-maintenance

**Comment by rafalp** [comment]
Yes, [this line](https://github.com/rafalp/Misago/blob/0.18.x/frontend/src/components/StartSocialAuth.js#L15) returns `undefined`, but react expects components to return JSX or `null`.
