### ISSUE TITLE
Unable to see user menu

### ISSUE THREAD

**Issue by isgk** [rafalp/Misago#1018]
![screenshot from 2018-06-06 12 44 45](https://user-images.githubusercontent.com/32245762/41022537-81855c80-6987-11e8-87d3-eddf277492fe.png)

I'm using version 0.18.1.

**Comment by rafalp** [comment]
Hello, could you post the error being displayed in your browser's JavaScript console?

**Comment by einarf** [comment]
Your user might be missing an avatar?

**Comment by isgk** [comment]
@rafalp  Resolved, I was running `DEBUG = False` with `python manage.py runserver --insecure` for testing purpose.
Thanks. Have a great day.
