### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by mr-ant** [rafalp/Misago#1030]
Hi ,
According to the instructions, I had a problem when I installed the development environment. After the execution `docker-compose up`, the page and the site are different. What else do I need to operate? Please see the picture below, thank you.
![snipaste_2018-07-13_11-22-04](https://user-images.githubusercontent.com/30248192/42670706-05155bb2-868f-11e8-9725-1125c11a35f6.png)

**Comment by rafalp** [comment]
Hey Mr. Ant ;)

This is actually documented in our readme:

> Development Status: Big changes happening on master branch, use **latest release for working code**.

Sorry for confusion, I have plans to re-animate our master once I have released Misago 0.19, but this is still some time off. ;)

**Comment by rafalp** [comment]
Also, here is Misago 0.18.1 which is latest release:

https://github.com/rafalp/Misago/releases/tag/0.18.1
