### ISSUE TITLE
Cookiecutter for misago

### ISSUE THREAD

**Issue by mr-ant** [rafalp/Misago#1046]
Hi @rafalp
Just build a misago version of cookiecutter, It's easy to use, start and run can read cookiecutter-django's doc. and my site is run with it . checkout and test it, if you have time.
Deploy and develop with docker,from now works fine.
[cookiecutter-misago](https://github.com/mr-ant/cookiecutter-misago)

**Comment by rafalp** [comment]
This is very nice, but please don't use github issues for general project discussion. We have [official forums](https://misago-project.org/) for that, and posting there you will have chance to reach many more people with your project.

Thanks!

**Comment by rafalp** [comment]
But on sidenote, this may be an alternative to `misago-docker` that we have been after for some time.

@einarf, could you find a minute and offer an comment? Perhaps caddy would make simpler alternative to nginx + letsencryopt companion in our setup?

**Comment by mr-ant** [comment]
No longer maintain this, use misago_docker deployment.
