### ISSUE TITLE
graphql & graphql-subscriptions

### ISSUE THREAD

**Issue by quickerlab** [rafalp/Misago#1048]
This is a great project, I'm very like the awards, ranking system and private threads.
Received event that to we plan use GraphQL interface as API? This will be great.
So, any plan to use graphql-subscriptions for notifications? such as like, follow, watch, mention, etc. And for mobile APP to receive realtime events.

**Comment by rafalp** [comment]
There's is no tracking issue for that yet, but I've postponed the planned frontend rewrite for when Misago implements GraphQL API offering the feature parity to current REST API. Once GraphQL is implemented, I will be either removing current REST API, or limiting it to just few endpoints for possible integrations/widgets.

I haven't made any plans about subscriptions or real-time yet, but currently any possible real-time implementations would be seriously hampered by the lack of real-time support in Django framework, which only plants to include those as part of 3.0 release, that is likely years from now. So the best we could hope for now would be `<Query pollInterval={500}>` in Apollo-Client.

**Comment by quickerlab** [comment]
thanks. Got it.

**Comment by rafalp** [comment]
Already in v4.
