### ISSUE TITLE
agreement problem。

### ISSUE THREAD

**Issue by mr-ant** [rafalp/Misago#1064]
Hi，
After add <Terms of service> and <Privacy policy>，those two agreements will not auto add to footer.
Misago version 0.19.0.

**Comment by rafalp** [comment]
Are you using Misago from PIP or github release?

**Comment by mr-ant** [comment]
github release.

**Comment by rafalp** [comment]
http://misago-project.org uses github release and footer legal links are working on it.

Did you customize the `footer.html`?

**Comment by mr-ant** [comment]
Yes, you are right,after update `footer.html`,this problem gone.Thanks.
