### ISSUE TITLE
Rate limiting?

### ISSUE THREAD

**Issue by yangnw** [rafalp/Misago#1098]
Instead of setting up the environment and test scripts, I decide to simply ask here. Is there rate limiting in Misago?
Since it's using django, I'd expect something like jsocol/django-ratelimit, which limits by IP. But more importantly, is there any limit for a user to add new threads, etc.?

**Comment by rafalp** [comment]
Hi!

Misago implements custom ratelimiting mechanism that lets you define minimal pause between posting next message, as well as daily limit of new posts and new threads.

Those limits are per application user, and not IP address.

**Comment by rafalp** [comment]
Closing due to lack of follow-up from OP ;)
