### ISSUE TITLE
Move caching utils from misago.core to misago.cache

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#1137]
I'm thinking now that Misago has reached the complexity when its good idea to break down some of modules. First comes `misago.core` that is catch-all for utilities and features shared by other features.

Caching utils could be extracted to dedicated `misago.cache` app for simplicity.

**Comment by mr-ant** [comment]
I also think we should split the Attachment as a standalone app.

**Comment by rafalp** [comment]
Yup, `misago.core`, `misago.users` and `misago.threads` are massive apps that could use breaking down into smaller ones. I will be tackling those as time allows me to, but priority is making it easier to customize Misago from admin panel, and for that I need easier caching and db configuration. ;)

**Comment by rafalp** [comment]
This is now implemented on master
