### ISSUE TITLE
Update social auth to 2.0

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#1151]
Python social auth 2.0 has been released a while ago including fixes to bugs that forced to me to use `misago-social-auth` fork in Misago.

**Comment by ali-alsabbah** [comment]
How do I go about fixing this?

**Comment by rafalp** [comment]
First you should make sure you've got Misago up and running on your machine.

You will have to edit `requirements.in`, remove `misago-social-auth-app-django` line from it and add `social-auth-app-django` instead.

Next create new `requirements.txt` using following pip-compile (`pip install pip-tools`) command:

```
pip-compile --output-file requirements.txt requirements.in
```

If tests pass thats it ;) If not, I'll be there to answer any questions you may have about this.

Thank you!
