### ISSUE TITLE
Make misago apps pass pylint checks

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#1161]
Pylint tends to be annoying, but it can catch some very surprising mistakes in the code, so it would be good idea to run it against Misago codebase.

**Comment by ali-alsabbah** [comment]
I would like to work on this if you don't mind providing a little guidance.

Do I just clone the directory and run pylint on it?

**Comment by rafalp** [comment]
@ali-alsabbah thank you for offering help - it means a great deal when people take time to do this. 👍

I already have unpushed branch that makes entire codebase pass for pylint, so don't bother ;)

**Comment by rafalp** [comment]
Here's PR: #1165

**Comment by rafalp** [comment]
@ali-alsabbah if you want to help out, could you please give #1151 a look?
