### ISSUE TITLE
Add Celery to Misago

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#1171]
There are parts of Misago that take considerable time to process, do blocking IO or could be ran periodically to perform maintenance and could be moved Celery.

Initially we could just get celery working in dev docker, and turn welcome email after user registration into a Celery task.

Related to #480

**Comment by ali-alsabbah** [comment]
Let me know how to start and I'll get going with this

**Comment by rafalp** [comment]
This one will be tricky, so I'll break it down in steps:

1. Make sure you open PR as soon as you've created new branch, so your work is open for review as soon as it started.
2. `docker-compose.yml` has to be edited to include redis service. Redis is in-memory key-value storage, but it supports messaging, so it can be used to send messages in celery. For example how to setup redis look at misago_docker's `docker-compose.yml`
3.  you will need to add celery and django-celery to `requirements.in` and rebuild `requirements.txt` (you should have plenty of practice here ;)).
4. you will need to copy `misago` service defined in `docker-compose.yml` and name copy `celery`. You will also have to update the `command` to start celery instead of `python manage.py runserver`
5. you will need to update `devproject/settings.py` to include `celery`

**Comment by ali-alsabbah** [comment]
Sounds good. I'll try to get it done in the next couple days.

**Comment by rafalp** [comment]
Fixed with #1176
