### ISSUE TITLE
cropit is not a function

### ISSUE THREAD

**Issue by LingCn** [rafalp/Misago#1183]
cropit is not a function，After the front end uses gulp build, an error is reported when setting a new avatar. Cropit is not a function

**Comment by aforwardz** [comment]
Hello, I came cross the same error, how you solved this problem?

**Comment by rafalp** [comment]
@aforwardz can you share the error? I never reproduced the problem that LingCn reported.

**Comment by aforwardz** [comment]
> @aforwardz can you share the error? I never reproduced the problem that LingCn reported.

Thanks for your reply! I wanna change my avatar and after I uploaded the image, the image was not previewed and the error logged out on the console as below: 

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/19967761/186634389-78555a67-a665-4cad-a63e-6db8bb6a25c5.png">

**Comment by rafalp** [comment]
Thanks. Is this on master or forum running with misago-docker?

**Comment by aforwardz** [comment]
I forked the repo based on v0.27.0 and it's not running with misago-docker but development env directly on my server

**Comment by rafalp** [comment]
I've moved frontend pipeline away from gulp to webpack.js and I've had this issue happen for me, but I've fixed it on master.
