### ISSUE TITLE
non docker setup

### ISSUE THREAD

**Issue by kahurani** [rafalp/Misago#1205]
it looks like misago is written exclusively with docker in mind[1]. it is possible i am missing out on something. it occurs to me that a lot of development happens without docker and if you are setting up misago on heroku for instance, you have to figure out to run it without docker. in other words, i think misago bending too much onto docker(unless i am missing some information). i am trying to set up misago on heroku and can document whatever information and code i think is important in my steps if you think it could be added to misago.

[1] #991

**Comment by rafalp** [comment]
Thank you for asking,

Misago is an open source project build using open technologies. Any developer familiar with [Django framework](https://www.djangoproject.com/) and software stack used will have no trouble to deploy Misago their way, without Docker.

> i am trying to set up misago on heroku and can document whatever information and code i think is important in my steps if you think it could be added to misago.

By all means please post your findings on [project forums](https://misago-project.org/)! I know some people have tried running Misago on Heroku. Problems reported so far are [lack of cron](https://misago-project.org/t/cron-jobs/622/) and [uploaded files disappearing on free dynos](https://misago-project.org/t/user-avatars-disappearing-on-heroku/546/).

> it occurs to me that a lot of development happens without docker and if you are setting up misago [...] i think misago bending too much onto docker(unless i am missing some information).

Few months ago I've made a decision for Docker being recommended way for Misago deployments. Docker enables me to limit setup process to few steps that are easy to document and follow by others. 

I understand where you are coming from, but it in practice it doesn't work for projects like Misago. A lot of development happens without Docker, but a lot more people want to just get site up and running with minimal effort, and Docker enables just that. It also makes setup easy to document and lets software developers hide complexity behind `docker-compose build && docker-compose up`, making software open and easy for extending without making setup and updates increasingly more complex.

Thanks!

**Comment by kahurani** [comment]
hello @rafalp 

> Thank you for asking,
> 

i am not sure why you closed this issue so quickly.

> Misago is an open source project build using open technologies. Any developer familiar with [Django framework](https://www.djangoproject.com/) and software stack used will have no trouble to deploy Misago their way, without Docker.

any developer familiar with django could deploy misago their way without docker but the effort they'd have to put into this is a lot compared to how you could just easily get this running with docker and that's because no effort has been put into that.

you have put all the effort into misago and in the process forgot everything else.

> 
> > i am trying to set up misago on heroku and can document whatever information and code i think is important in my steps if you think it could be added to misago.
> 
> By all means please post your findings on [project forums](https://misago-project.org/)! I know some people have tried running Misago on Heroku. Problems reported so far are [lack of cron](https://misago-project.org/t/cron-jobs/622/) and [uploaded files disappearing on free dynos](https://misago-project.org/t/user-avatars-disappearing-on-heroku/546/).
> 
> > it occurs to me that a lot of development happens without docker and if you are setting up misago [...] i think misago bending too much onto docker(unless i am missing some information).
> 
> Few months ago I've made a decision for Docker being recommended way for Misago deployments. Docker enables me to limit setup process to few steps that are easy to document and follow by others.
> 
> I understand where you are coming from, but it in practice it doesn't work for projects like Misago. A lot of development happens without Docker, but a lot more people want to just get site up and running with minimal effort, and Docker enables just that. It also makes setup easy to document and lets software developers hide complexity behind `docker-compose build && docker-compose up`, making software open and easy for extending without making setup and updates increasingly more complex.

i understand why docker comes in handy in development but that doesn't mean you shouldn't work things that would make development without docker easier.

> 
> Thanks!

since i'm working without docker, i thought that if i come across something i think is worthwhile, i could always make a PR. are you of a similar opinion?

**Comment by rafalp** [comment]
> i am not sure why you closed this issue so quickly.

From your original message I've got the idea that you are proposing preparing instructions/pointers for heroku setup without docker. My previous message addressed this point, thus close ;)

> that's because no effort has been put into that.

I can assure you that during the last 8 years this project exists I was *actively* pursuing different ways for making Misago more approachable for people but before Docker nothing really worked for the users.

> since i'm working without docker, i thought that if i come across something i think is worthwhile, i could always make a PR. are you of a similar opinion?

I will be happy to merge PR's that make things easier for non-docker crowd if they don't complicate things and don't increase possible burden on me in the future.

Btw. Is there any reason why you *can't* use docker for local development?

**Comment by kahurani** [comment]
> 
> I can assure you that during the last 8 years this project exists I was _actively_ pursuing different ways for making Misago more approachable for people but before Docker nothing really worked for the users.

i have not used docker before, from looking at this there are a lot of things relating to docker that i don't really understand and i would like to think that it takes a lot of work to come up with the docker setup but from there, things are really easy for the users.

> 
> I will be happy to merge PR's that make things easier for non-docker crowd if they don't complicate things and don't increase possible burden on me in the future.
> 
> Btw. Is there any reason why you **can't** use docker for local development?

i'll to take this into consideration if i work on anything.

i **can** use docker for local development. i am just not used to that.

**Comment by rafalp** [comment]
> takes a lot of work to come up with the docker setup

Yes, but when the application has docker setup, starting development instance is a three-step process:

1. Install docker
2. Run `docker-compose build` in project's directory
3. Run `docker-compose up` to start Misago

Compare above to process without docker:

1. Create python virtualenv and install dependencies to it
2. Setup PostgreSQL database
3. Install Redis instance
4. Setup PostgreSQL and Redis connections
5. Start celery worker next to devserver

The above process takes hours to complete and is basically impossible for anyone unfamiliar with Python. And unfamiliarity with Python is a valid concern here because you may be a frontend dev starting Misago on your machine only so you can customize the way it looks for your live site.

Docker has other advantages for us like ability to quickly spin up additional instances, or reset dev instance to clean state to test migrations or mock data generation.

**Comment by kahurani** [comment]
i am not sure but it is possible to automate the above steps using something like ansible. that way the user only runs an ansible script which installs the virtual environment, installs dependencies, postgresql database, redis instance etc. this is an idea i just came up with and i have not seen anyone do this before but this is a very lightweight solution compared to using docker.

other than that, i'd admit that the common/most used way of getting around the issue we are discussing is by using docker.

**Comment by kahurani** [comment]
i suspect i'll not be able to work on this but this can totally be done without docker.

**Comment by rafalp** [comment]
> i suspect i'll not be able to work on this but this can totally be done without docker.

This is not the matter of something being totally doable without docker or not, because I've never said it's not - it's just annoyingly hard. ;)

However, if nobody will work on it, things will not change.

> it is possible to automate the above steps using something like ansible

You could probably even automate it writing bash script, but ansible (and other tech that doesn't isolate its env from host) raises some questions:

- How easy it is to install orchestration tech?
- How dependent on the current state of the host is the setup?
- How repeatable and reproducible are created environments?
- What is the plan for users on different platforms? We have minimal alternative instruction for Docker for Windows that works.

> lightweight solution compared to using docker

Docker ran on linux is the lightweight solution, because it's not the virtualization tech like, say, Vagrant. Containers use Linux kernel cgroups feature for isolating user spaces from each other, which is both minimal overhead and near-native performance.

**Comment by kahurani** [comment]
> 
> Docker ran on linux is the lightweight solution, because it's not the virtualization tech like, say, Vagrant. Containers use Linux kernel cgroups feature for isolating user spaces from each other, which is both minimal overhead and near-native performance.

you're right. i don't know much about containers but on a bit of research it does look like these kinds of problems are exactly what containers are for.

**Comment by kahurani** [comment]
> 
> Yes, but when the application has docker setup, starting development instance is a three-step process:
> 
> 1. Install docker
> 2. Run `docker-compose build` in project's directory
> 3. Run `docker-compose up` to start Misago
> 

or, maybe let's just start here, the steps you have above and the steps you have listed on the Readme.md don't work, at least for me. for instance, following what you have just above gives me this:

i can install docker just find and build okay but `docker-machine up` gives me this:

```
(MAL) [kahurani@saffron Misago]$ docker-compose up 
Starting misago_postgres_1 ... done
Starting misago_redis_1    ... done
Starting misago_celery_1   ... done
Starting misago_misago_1   ... done
Attaching to misago_redis_1, misago_postgres_1, misago_celery_1, misago_misago_1
postgres_1  | 2019-03-04 09:56:45.325 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
redis_1     | 1:C 04 Mar 2019 09:56:45.204 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1     | 1:C 04 Mar 2019 09:56:45.205 # Redis version=5.0.3, bits=64, commit=00000000, modified=0, pid=1, just started
postgres_1  | 2019-03-04 09:56:45.325 UTC [1] LOG:  listening on IPv6 address "::", port 5432
redis_1     | 1:C 04 Mar 2019 09:56:45.205 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
postgres_1  | 2019-03-04 09:56:45.327 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
redis_1     | 1:M 04 Mar 2019 09:56:45.209 * Running mode=standalone, port=6379.
postgres_1  | 2019-03-04 09:56:45.357 UTC [21] LOG:  database system was shut down at 2019-03-04 09:56:36 UTC
redis_1     | 1:M 04 Mar 2019 09:56:45.209 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1     | 1:M 04 Mar 2019 09:56:45.209 # Server initialized
redis_1     | 1:M 04 Mar 2019 09:56:45.210 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1     | 1:M 04 Mar 2019 09:56:45.210 * DB loaded from disk: 0.000 seconds
misago_1    | python: can't open file 'manage.py': [Errno 2] No such file or directory
misago_misago_1 exited with code 2
celery_1    | Traceback (most recent call last):
celery_1    |   File "/usr/local/bin/celery", line 10, in <module>
celery_1    |     sys.exit(main())
celery_1    |   File "/usr/local/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
celery_1    |     _main()
celery_1    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
celery_1    |     cmd.execute_from_commandline(argv)
celery_1    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
celery_1    |     super(CeleryCommand, self).execute_from_commandline(argv)))
celery_1    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 273, in execute_from_commandline
celery_1    |     argv = self.setup_app_from_commandline(argv)
celery_1    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 479, in setup_app_from_commandline
celery_1    |     self.app = self.find_app(app)
celery_1    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 501, in find_app
celery_1    |     return find_app(app, symbol_by_name=self.symbol_by_name)
celery_1    |   File "/usr/local/lib/python3.6/site-packages/celery/app/utils.py", line 359, in find_app
celery_1    |     sym = symbol_by_name(app, imp=imp)
celery_1    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 504, in symbol_by_name
celery_1    |     return imports.symbol_by_name(name, imp=imp)
celery_1    |   File "/usr/local/lib/python3.6/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
celery_1    |     module = imp(module_name, package=package, **kwargs)
celery_1    |   File "/usr/local/lib/python3.6/site-packages/celery/utils/imports.py", line 104, in import_from_cwd
celery_1    |     return imp(module, package=package)
celery_1    |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
celery_1    |     return _bootstrap._gcd_import(name[level:], package, level)
celery_1    |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
celery_1    |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
celery_1    |   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
celery_1    | ModuleNotFoundError: No module named 'devproject'
misago_celery_1 exited with code 1
```

i seem to get a similar error with the steps you have on the readme so maybe this is something you can look at. i mean, i just followed the steps exactly as you have them so it's quite possible something simple is missing out.

**Comment by rafalp** [comment]
> python: can't open file 'manage.py': [Errno 2] No such file or directory
misago_misago_1 exited with code 2

Which directory you are running those commands in? They should be ran in repo's main directory.

**Comment by kahurani** [comment]
> 
> Which directory you are running those commands in? They should be ran in repo's main directory.

i am actually running this from the repo's main directory. see below:

`[kahurani@saffron Misago]$ pwd 
/home/kahurani/Misago
[kahurani@saffron Misago]$ ls
Dockerfile  LICENSE.rst  MANIFEST.in  README.rst  dev  devproject  docker-compose.yaml  frontend  manage.py  misago  pytest.ini  requirements.in  requirements.txt  setup.py
[kahurani@saffron Misago]$`

`docker-compose build` runs successfully or so i think:

`[kahurani@saffron Misago]$ docker-compose build
postgres uses an image, skipping
redis uses an image, skipping
Building misago
Step 1/9 : FROM python:3.6
 ---> 70f6aab434cf
Step 2/9 : ENV PYTHONUNBUFFERED 1
 ---> Using cache
 ---> ab2490f3b264
Step 3/9 : ENV IN_MISAGO_DOCKER 1
 ---> Using cache
 ---> 12c1e871d88d
Step 4/9 : RUN apt-get update && apt-get install -y     vim     libffi-dev     libssl-dev     sqlite3     libjpeg-dev     libopenjp2-7-dev     locales     cron     postgresql-client     gettext
 ---> Using cache
 ---> 0fde2ac0bbd6
Step 5/9 : ADD requirements.txt /
 ---> Using cache
 ---> b9fda685eafb
Step 6/9 : RUN pip install --upgrade pip && pip install -r requirements.txt
 ---> Using cache
 ---> 3babf01ceadb
Step 7/9 : WORKDIR /srv/misago
 ---> Using cache
 ---> dee88a664b6f
Step 8/9 : EXPOSE 8000
 ---> Using cache
 ---> 91e0b513ffd7
Step 9/9 : CMD python manage.py runserver 0.0.0.0:8000
 ---> Using cache
 ---> 8a05660336b6
Successfully built 8a05660336b6
Successfully tagged misago_misago:latest
Building celery
Step 1/9 : FROM python:3.6
 ---> 70f6aab434cf
Step 2/9 : ENV PYTHONUNBUFFERED 1
 ---> Using cache
 ---> ab2490f3b264
Step 3/9 : ENV IN_MISAGO_DOCKER 1
 ---> Using cache
 ---> 12c1e871d88d
Step 4/9 : RUN apt-get update && apt-get install -y     vim     libffi-dev     libssl-dev     sqlite3     libjpeg-dev     libopenjp2-7-dev     locales     cron     postgresql-client     gettext
 ---> Using cache
 ---> 0fde2ac0bbd6
Step 5/9 : ADD requirements.txt /
 ---> Using cache
 ---> b9fda685eafb
Step 6/9 : RUN pip install --upgrade pip && pip install -r requirements.txt
 ---> Using cache
 ---> 3babf01ceadb
Step 7/9 : WORKDIR /srv/misago
 ---> Using cache
 ---> dee88a664b6f
Step 8/9 : EXPOSE 8000
 ---> Using cache
 ---> 91e0b513ffd7
Step 9/9 : CMD python manage.py runserver 0.0.0.0:8000
 ---> Using cache
 ---> 8a05660336b6
Successfully built 8a05660336b6
Successfully tagged misago_celery:latest
[kahurani@saffron Misago]$ `

run from the same directory.

**Comment by kahurani** [comment]
@rafalp since you have failed to give me any directions. i have finally got from the readme that i am supposed to ask such things from the forums(which is probably what you expect me to do) but as you have failed to direct me, i will consequently **not** be asking about this issue in the forums.

**Comment by rafalp** [comment]
@kahurani I am sorry that open source project worked on in free time and provided to you for free in hopes that it will be useful was enough for you to react so aggressively.

:(

**Comment by rafalp** [comment]
Next step for debugging this would be doing the `docker-compose run --rm misago ls` that will list all files in the "misago" container. If `manage.py` is present here then I'm suprised by behaviour.

Maybe `docker-compose build --no-cache` would fix the issue?

**Comment by kahurani** [comment]
@rafalp i have tried what you have above though it doesn't seem to help. 

anyways, more on this issue in the forums.

thanks for the help so far so good.

**Comment by rafalp** [comment]
`docker-compose run --rm misago ls` should print list of files inside docker container. Can you paste here the output?

**Comment by kahurani** [comment]
hello,

i have done that but can't see anything relevant.

`(MisagoDev) [kahurani@saffron Misago]$ docker-compose run --rm misago ls
Starting misago_redis_1 ... done
Starting misago_postgres_1 ... done
(MisagoDev) [kahurani@saffron Misago]$ 
`

**Comment by rafalp** [comment]
This is super weird and first time I am seeing that.

What happens if you run `ls` (without `docker-compose run --rm misago`)  in same directory?

**Comment by kahurani** [comment]
`ls` does work as usual, see below,

```
[kahurani@saffron Misago]$ ls
Dockerfile  LICENSE.rst  MANIFEST.in  README.rst  dev  devproject  docker-compose.yaml  frontend  manage.py  misago  pytest.ini  requirements.in  requirements.txt  setup.py
[kahurani@saffron Misago]$
```

**Comment by rafalp** [comment]
Can you try using the `./dev reset` and see if that changes anything?

What is your OS? Is it Linux? Virtual machine? Windows with linux subsystem?

**Comment by kahurani** [comment]
```
[kahurani@saffron Misago]$ uname -a
Linux saffron 4.20.13-arch1-1-ARCH #1 SMP PREEMPT Wed Feb 27 19:10:28 UTC 2019 x86_64 GNU/Linux
[kahurani@saffron Misago]$ 

```

that took a bit of time. my connection is a bit slow so, yeah but `./dev reset` just takes me back to the same place. running a python shell in the container like i showed above doesn't get me any files.

**Comment by kahurani** [comment]
@rafalp can you please confirm that the image resulting from the development dockerfile works for you. because, it clearly doesn't work for me.

**Comment by rafalp** [comment]
I can confirm that docker setup works on current master. Zero errors.

**Comment by kahurani** [comment]
> I can confirm that docker setup works on current master. Zero errors.

that's just what i needed someone to confirm, thanks a lot.

> 
> What is your OS? Is it Linux? Virtual machine? Windows with linux subsystem?

i don't think you should bother yourself with this issue anymore.
