### ISSUE TITLE
FATAL:  password authentication failed for user "misago_vY5xkg6FIaEv0Kbj"

### ISSUE THREAD

**Issue by yingzongliang** [rafalp/Misago#1210]
I have installed the misago on my personal computer following the instruction. 

Finished the installation, I used the commond 
./appctl manage.py runserver to start the webpages, but the following question appeared. 

FATAL:  password authentication failed for user "misago_vY5xkg6FIaEv0Kbj"

How could I fix it.

**Comment by rafalp** [comment]
`./appctl` is not for development - its for running live Misago forums. Please follow guide in this repository's readme to run Misago on personal computer ;)
