### ISSUE TITLE
Quote/Spoiler BBCode are parsed before inline code markdown

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#1268]
This code will cause spoiler tag to start in wrong place:

```markdown
Lorem ipsum `[spoiler]`

[spoiler]
Dolor met sit amet
[/spoiler]
```

**Comment by rafalp** [comment]
This one will be tricky to handle, because it's executed after `code` block, but before the `backtick` (inline code) block. It may have to wait for before we will move away from server-side parser to client-side WYSIWYG editor representing documents as json.

**Comment by rafalp** [comment]
Fixed by #1290

**Comment by AetherUnbound** [comment]
Wait, was this one really fixed by #1290?

**Comment by rafalp** [comment]
Nope, my comment about 1290 was made by mistake. Still, I'll mark this issue as wont-fix due to reasons I've posted on 27 July.

**Comment by AetherUnbound** [comment]
I've noticed too that it's not possible to quote spoilered text properly as well. An empty spoiler block appears before the un-spoilered quoted text. I'm sure this is caused by the same issue, but at least worth mentioning here.
