### ISSUE TITLE
need to call super().filter_threads() in threads viewmodel!

### ISSUE THREAD

**Issue by hamid-moghadam** [rafalp/Misago#1275]
shouldn't we call `super().filter_threads(request,threads)` if we override it in forum and private threads !? i have a context that for both of them i need to do a same specific job. i think they should either always call their super class(ViewModel) in `threads/viewmodels/threads.py` or based on requirement we call it!

**Comment by rafalp** [comment]
No, we shouldn't, this function is purposefully an noop in the base class.

Can you share what job do you need those to do?

**Comment by hamid-moghadam** [comment]
The way i want to do it is like `get_base_queryset` in ViewModel(`threads/viewmodels/threads.py`) that you called it in PrivateThread(`queryset = super().get_base_queryset(request, threads_categories, list_type)`).

i need to do sth and apply it in both thread types(Forum and Private) so i conclude that it would better to put that logic in parent(`ViewModel`) to prevent messy code.

we are developing some new features to "Misago" based on our project requirements. some of them are "bookmark", "label","invitation" and so on...


i'm trying to send pull requests soon :)
i'm new to open source community. what are prerequisites to consider for Misago in order to "pull request" new features?

**Comment by rafalp** [comment]
> i'm new to open source community. what are prerequisites to consider for Misago in order to "pull request" new features?

You can simply create pull request ;)

However I am thinking that you should put your filter logic in custom function, and call it in both view-models. Making this hook always run shared logic kind of defeats point behind it IMHO, and you've didn't provide the example other than "to do something and apply" ;)

**Comment by hamid-moghadam** [comment]
> You can simply create pull request ;)

thanks. i'll do it soon...

> However I am thinking that you should put your filter logic in custom function, and call it in both view-models. Making this hook always run shared logic kind of defeats point behind it IMHO, and you've didn't provide the example other than "to do something and apply" ;)

:)
it was a case that i wanted to check whether thread is bookmarked or not(a simple query). that's why i tried to do it in `ForumThreads`. afterward i noticed it doesn't applied to `PrivateThreads`. so after considering "threads viewmodels", i put the logic(`is_bookmarked = len(thread.bookmarks.filter(user_id=request.user.id, enable=True)) > 0`) in `ViewModel.filter_threads` method. but now i come to conclusion that its in wrong place and it has to be in `ThreadSerializer`.

**Comment by rafalp** [comment]
Misgo already has a bookmarking system, but its called "subscription without notification" ;)

**Comment by hamid-moghadam** [comment]
yes you are right :(
because of needing a custom UI, we didn't check subscription completely(only email has been checked).
Thanks any way.

**Comment by rafalp** [comment]
Could you also describe "custom UI" you are speaking of? I would love to hear about that as I am planning plugin system for Misago.

**Comment by hamid-moghadam** [comment]
We are planning for it, i'll write you soon. it's about rethinking of UI/UX and mostly UX

**Comment by rafalp** [comment]
Thanks! I am super interested in what UI/UX changes you will come up with - I wish to do general overhaul of Misago's  UI/UX in one of the future versions, but I am currently mostly gathering ideas and researching things. ;)
