### ISSUE TITLE
Package installation error 

### ISSUE THREAD

**Issue by pradeep-raj** [rafalp/Misago#1276]
hi all, im new to misago, i try to setup misago==0.19.4 in local (ubuntu)system,
download all the files from repository,
now i run " pip2 install -r 'requirements.txt' " this command throw error message like,

    ERROR: Command errored out with exit status 1:
     command: /home/imi-005/Envs/misago_forum/bin/python2 -c 'import sys, setuptools, 
     tokenize; sys.argv[0] = '"'"'/tmp/pip-install-YOFNqS/starlette/setup.py'"'"'; __file__='"'"'/tmp/pip- 
     install-YOFNqS/starlette/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open (__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-YOFNqS/starlette/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-YOFNqS/starlette/setup.py", line 41, in <module>
        long_description=get_long_description(),
      File "/tmp/pip-install-YOFNqS/starlette/setup.py", line 22, in get_long_description
        with open('README.md', encoding="utf8") as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------                                                                                         
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Used platforms:
         1.  Django==1.11.15
         2.  python==2.7.12
         3.  misago==0.19.4 

i can't understand what is the exact error!
please help me, thanks in advance.

  

  
![dddddd](https://user-images.githubusercontent.com/42230889/62540040-47b0d880-b874-11e9-903e-cef66faa6e97.png)

**Comment by rafalp** [comment]
> 2. python==2.7.12

Here's your problem ;) Misago requires Python 3.6 or later to run.
