### ISSUE TITLE
force authentication everywhere!

### ISSUE THREAD

**Issue by hamid-moghadam** [rafalp/Misago#1277]
How to apply authentication everywhere (include views and apis)? i tried to do it in `UserMiddleware` with `return HttpResponseRedirect(reverse("misago:login"))` but i got "TOO MANY REDIRECTS" error and i think this is not a good place.

For example if user go to index page, we redirect him to login, and for the others we raise `PermissionDenied` exception.

How should i implement it?

**Comment by rafalp** [comment]
Please ask this question on [project forums](https://misago-project.org), as per our readme:

> For feature or support requests as well as general feedback please use official forum instead. Your feedback means much to the project so please do share your thoughts!

**Comment by rafalp** [comment]
(I guess I should finally setup issue template for this repo ;))

**Comment by hamid-moghadam** [comment]
:)
Ok. thank you. i'll do it right next time ;)
