### ISSUE TITLE
Signature modification not available even though users are allowed to edit their signature

### ISSUE THREAD

**Issue by AetherUnbound** [rafalp/Misago#1280]
I'm having an issue where I'm not seeing an option to edit my signature as a member even though the Member role has Signature set to "yes":
![image](https://user-images.githubusercontent.com/10214785/63313456-62923c80-c2b9-11e9-9fc1-58b8eccbc706.png)
![image](https://user-images.githubusercontent.com/10214785/63313466-6f169500-c2b9-11e9-821e-ee91c4e069ab.png)

Any idea why this might be the case? I've hunted all around for it. I can change it as a moderator for a user, but I don't want to have users send me their signatures to set :grin:

**Comment by rafalp** [comment]
Signatures are not implemented in the frontend 😅

I want to bring them back, but those are third on my current to-do list. ;)

**Comment by AetherUnbound** [comment]
Oh got it! Haha thanks for the heads up - I was poking around the backend code and it seemed like most of the pieces were there so I thought I must be missing something. Thanks! 😄

**Comment by rafalp** [comment]
For some extra context: current Misago codebase comes from big rewrite that was originally developed to be largely based on static pages and `html` templates, but in last 1/3 of development I've decided to move all interactivity to JSON API/JavaScript, so I've cut signatures from UI due to time constraints. Since then those lingered in the backend code (and are mostly complete), but I haven't really gone around to do it.

Still, my plan for next few Misago releases (after SSO) is to add some small-scale improvements:

- adding custom links to menus from admin panel
- enabling user signatures
- small layout improvements

**Comment by AetherUnbound** [comment]
Thanks for the context - I'm really looking forward to those changes! I'm also excited for some UI-based customizing of categories/general site colors (I seem to recall you mentioning that being on the roadmap).

I'm interested in helping, but I've never worked with Django and I'm not by any means a front-end developer 😅 I'm going to try and read up on those - I'd love to help out with some of these features!

**Comment by rafalp** [comment]
> UI-based customizing of categories/general site colors

This is already live as `Themes` interface in the admin, but I plan to add some extra customization support for categories so you can upload custom category's header background image, or use color from color picker.

**Comment by AetherUnbound** [comment]
I've poked around the Themes interface a bit, but it seems like the primary way to modify things is through CSS files that you upload. Since I can't export the default theme, it's hard to know what classes I should override to customize the different categories and such. I've checked out the documentation [here](https://misago.gitbook.io/docs/categorystyles#default-classes) as well on classes but I'm still not sure how best to do this. It's likely my unfamiliarity with Django/CSS, I'm probably missing something straightforward here.

**Comment by rafalp** [comment]
> Since I can't export the default theme, it's hard to know what classes I should override to customize the different categories and such.

Browser dev tools are your best friend. Inspect the item on site, see its CSS classes and what styles are coming from those and define your own.

> It's likely my unfamiliarity with Django

There is no Django involved in the process. The frontend uses Bootstrap 3 for CSS, and you can fork the `frontend` directory from the repo to get started with custom CSS, but simplest way is to create child theme to default theme - that way default CSS will still be included, but you will be able to add custom CSS to it.

**Comment by AetherUnbound** [comment]
Awesome, thanks a ton! I'll poke around with that 😁
