### ISSUE TITLE
Attachment size limit permission not respected

### ISSUE THREAD

**Issue by AetherUnbound** [rafalp/Misago#1288]
It doesn't look like the attachment size limit that's modifiable in the user role permission settings isn't being respected. I may not be setting this right, but here's the settings:

**Member role settings**
![image](https://user-images.githubusercontent.com/10214785/64752053-0c3ca600-d4d3-11e9-9280-7bcac1c530b7.png)

**Moderator role settings**
![image](https://user-images.githubusercontent.com/10214785/64752093-28404780-d4d3-11e9-81d4-57a5a51c1539.png)

**My user roles**
![image](https://user-images.githubusercontent.com/10214785/64752173-66d60200-d4d3-11e9-9315-4e22107bd8b9.png)

**Error message I'm receiving**
![image](https://user-images.githubusercontent.com/10214785/64752242-a6045300-d4d3-11e9-90e8-7fad7b44d2d4.png)

Is there another setting I'm missing?

**Comment by AetherUnbound** [comment]
Ah, it looks like there's a per-`AttachmentType` file size that may have higher priority over this setting

**Comment by AetherUnbound** [comment]
It seems to be this line that's getting that setting:
https://github.com/rafalp/Misago/blob/b16b5c6b726ca5e71cc5738e5d062d6c9d534b55/misago/threads/api/attachments.py#L32

**Comment by AetherUnbound** [comment]
Forgive me, I know nothing about ACL altogether, albeit in django 😁 
This looks like it might be where the issue is occurring?
https://github.com/rafalp/Misago/blob/b16b5c6b726ca5e71cc5738e5d062d6c9d534b55/misago/threads/permissions/attachments.py#L43-L58

**Comment by AetherUnbound** [comment]
Forgive me, I know nothing about ACL altogether, albeit in django 😁 
This looks like it might be where the issue is occurring?
https://github.com/rafalp/Misago/blob/b16b5c6b726ca5e71cc5738e5d062d6c9d534b55/misago/threads/permissions/attachments.py#L43-L58

**Comment by rafalp** [comment]
Attachment type limit overrides uploads limit for individual types:

https://github.com/rafalp/Misago/blob/master/misago/threads/api/attachments.py#L32
https://github.com/rafalp/Misago/blob/master/misago/threads/api/attachments.py#L89

**Comment by AetherUnbound** [comment]
Huh, it looks like the `request.user_acl["max_attachment_size"]` is the first "hard limit" that's tested though:
https://github.com/rafalp/Misago/blob/master/misago/threads/api/attachments.py#L90
Where does that number come from? I had just assumed it was the group permissions

**Comment by emawalekr01** [comment]
Can we use GITHUB public code on our [website](https://www.topbestnespresso.com)? Is there any copyright policy?

**Comment by rafalp** [comment]
@emawalekr01 

Misago is free and open source software. You can read license here: https://github.com/rafalp/Misago/blob/master/LICENSE.rst

Please ask on our [support forums](https://misago-project.org) in future. Asking unrelated questions in other people issues is found rude on GitHub ;)

**Comment by alicejohn1** [comment]
How can I use the GITHUB code on my [website](https://bestcoffeemaker2021.com/)?

**Comment by rafalp** [comment]
What's happening currently is there are two separate filesize checks:

- Check against user's upload limit, coming from their permissions
- Check against attachment type upload limit, coming from file type (if set)

So you can have user with permission to upload files that are 8mb in size, but file type they  are uploading is limited to 2mb. You are uploading 4mb file. First check will pass but second check will fail.

I will remove support for per-type upload limits in 0.30 but keep fields around. I will drop them altogether 1.0 I think.
