### ISSUE TITLE
Images are rendered with ! and () even if there is a space between the text

### ISSUE THREAD

**Issue by AetherUnbound** [rafalp/Misago#1289]
I've notice the markdown engine attempts to render an image based on `!` and `()` even if there's a space between the two characters. I've created a test of this on the forum: https://misago-project.org/t/image-markdown-test/845/

The respective text for all of these tests are:
`I love misago! (wahoo)`
`I love misago! (yes I do)`
`I love misago! (Yes. I do)`

**Comment by rafalp** [comment]
Looks like there's an optional whitespace character in regex for inline image: https://github.com/rafalp/Misago/blob/master/misago/markup/md/shortimgs.py#L5

Seems like easy enough fix to land in 0.23.

Thanks for reporting!

**Comment by AetherUnbound** [comment]
Ooo, I'd love to jump in and fix that! :) Feel free to assign this one to me.
