### ISSUE TITLE
Linking outside Sites

### ISSUE THREAD

**Issue by DigitDaemon** [rafalp/Misago#1296]
Is there a way that hyperlinks could by default open new tabs instead of redirecting the current one?

**Comment by mattbowden-ookla** [comment]
I believe the place to make this adjustment would be here: 
https://github.com/rafalp/Misago/blob/master/misago/markup/bbcode/inline.py#L81-L96

@rafalp would it be bad to make that default behavior?

**Comment by AetherUnbound** [comment]
I believe the place to make this adjustment would be here: https://github.com/rafalp/Misago/blob/master/misago/markup/bbcode/inline.py#L81-L96

@rafalp would it be bad to make that default behavior?

**Comment by rafalp** [comment]
`bbcode.inline` only adds support for `[url]` BBCode, it doesn't affect the behavior of the other url's that users post in their messages.

I feel that best way to go about this should be implementing custom posting middleware that would do another pass-over on post content before its saved. Misago also has [parsing pipeline](https://github.com/rafalp/Misago/blob/master/misago/markup/pipeline.py) that was intended to provide proper extension point for "just" the parser, but that one didn't go anywhere. Perhaps its worth picking up in future releases?

**Comment by rafalp** [comment]
Let's actually factually do this.
