### ISSUE TITLE
How to install it on local machine?

### ISSUE THREAD

**Issue by rade98** [rafalp/Misago#1310]
How to install misago on local comp?

**Comment by rafalp** [comment]
There is a guide in the readme: [Development](https://github.com/rafalp/Misago#development).

**Comment by rade98** [comment]
Thanks!

**Comment by rade98** [comment]
I'm having error like

> At line:1 char:91
> + ... ; $ProgressPreference = 'SilentlyContinue'; apt-get update && apt-get ...
> +                                                                ~~
> The token '&&' is not a valid statement separator in this version.
>     + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordEx
>    ception
>     + FullyQualifiedErrorId : InvalidEndOfLine
> 
> ERROR: Service 'misago' failed to build: The command 'powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; apt-get update && apt-get install -y     vim     libffi-dev     libssl-dev     sqlite3     libjpeg-dev     libopenjp2-7-dev     locales     cron     postgresql-client     gettext' returned a non-zero code: 1


How to fix it?

**Comment by rafalp** [comment]
Are you using latest docker with docker compose installed?

**Comment by rade98** [comment]
Here is what I have.
docker-compose version 1.24.1, build 4667896b
Docker version 19.03.1, build 74b1e89

**Comment by rafalp** [comment]
Are you sure you are using linux containers in your docker?.

**Comment by rade98** [comment]
Actually it was Windows, sorry. Now when I changed I have issue like 

> /bin/sh: 1: Syntax error: end of file unexpected
> ERROR: Service 'misago' failed to build: The command '/bin/sh -c pip install --upgrade pip &&     pip install -r requirements.txt &&     pip install -r requirements-plugins.txt &&' returned a non-zero code: 2

**Comment by rade98** [comment]
I just deleted && and it works. But now when I continue I have this.

> Status: Downloaded newer image for redis:5
> Creating misago-master_postgres_1 ... done                                                                              Creating misago-master_redis_1    ... done                                                                              ERROR: Cannot create container for service misago: b'Drive has not been shared'
