### ISSUE TITLE
SAML support

### ISSUE THREAD

**Issue by FFY00** [rafalp/Misago#1315]
Hey, would it be possible to implement SAML authentication support? Right now we already have an external authentication provider system but this would need work a bit differently. This would replace the normal authentication system.

https://github.com/onelogin/python3-saml seems like a good candidate.

I think the easiest way to setup a SAML server for development would be using keycloak.

**Comment by rafalp** [comment]
Hi!

I've no experience with SAML myself, but perhaps this could be done with a plugin overriding the default SSO implementation? 🤔
