### ISSUE TITLE
manage.py migrate: error: unrecognized arguments: migrations

### ISSUE THREAD

**Issue by imvieira** [rafalp/Misago#1319]
$ docker-compose run --rm misago python manage.py migrate - runs migrations
Creating network "misago_default" with the default driver
Pulling postgres (postgres:10)...
10: Pulling from library/postgres
Digest: sha256:3263c8dad1b5aa6be80144786b18515910165ed771863d686c8b8fda30fea1ad
Status: Downloaded newer image for postgres:10
Pulling redis (redis:5)...
5: Pulling from library/redis
Digest: sha256:fe80393a67c7058590ca6b6903f64e35b50fa411b0496f604a85c526fb5bd2d2
Status: Downloaded newer image for redis:5
Creating misago_postgres_1 ... done
Creating misago_redis_1    ... done
usage: manage.py migrate [-h] [--noinput] [--database DATABASE] [--fake]
                         [--fake-initial] [--plan] [--run-syncdb] [--version]
                         [-v {0,1,2,3}] [--settings SETTINGS]
                         [--pythonpath PYTHONPATH] [--traceback] [--no-color]
                         [--force-color]
                         [app_label] [migration_name]
manage.py migrate: error: unrecognized arguments: migrations

**Comment by rafalp** [comment]
The part after dash is explanation from readme, not part of command you're supposed to run ;)

**Comment by imvieira** [comment]
oh ok! haha
