### ISSUE TITLE
Portuguese version

### ISSUE THREAD

**Issue by imvieira** [rafalp/Misago#1320]
Hi,

The idiom portuguese is one of languages most spoken in the world. Brazil and Portugal are native portuguese.
I would like to contribute to the portuguese translation , at leat for the main words like "Threads", posts, registration etc.
Please, I was wondering if I can contribute, and then, how can I ? Thank you

**Comment by rafalp** [comment]
Thanks for offering your help! I believe week ago other person announced that they are looking for help in translating Misago to this language. You can find this on Misago forums: https://misago-project.org/t/brasileiros-por-aqui/857/

**Comment by rafalp** [comment]
Thanks for offering your help! I believe week ago other person announced that they are looking for help in translating Misago to this language. You can find this on Misago forums: https://misago-project.org/t/brasileiros-por-aqui/857/
