### ISSUE TITLE
Alter legal error from memche cache

### ISSUE THREAD

**Issue by ChandlerBent** [rafalp/Misago#1341]
misago.legal.utils
```python
    cache_name = "misago_legal_%s_%s" % (agreement.pk, agreement.last_modified_on or "")
```

The problem is here. `agreement.last_modified_on`. 
Some cache database engine key does not support whitespace. Example: Memcache

Datetime default format string has whitespace.
`last_modified_on` should use `strftime`.

```python
    cache_name = "misago_legal_%s_%s" % (agreement.pk, agreement.last_modified_on.strftime('%Y-%m-%d_%X') if agreement.last_modified_on else '')
```

**Comment by rafalp** [comment]
Thank you for report, but we don't support cache engines other than Redis. which is part of `misago-docker`.
