### ISSUE TITLE
the theme like shown on the preview page is still exist?

### ISSUE THREAD

**Issue by PROgramJEDI** [rafalp/Misago#1344]
the blue template as shown on the README page of the project [https://camo.githubusercontent.com/993c6aeb9bccfabc9b1215db23722a63e447ab18/68747470733a2f2f6d697361676f2d70726f6a6563742e6f72672f6d656469612f6d706f72672d686f6d652d736d616c6c2e706e673f3031303632303138]

is still exist? and how can I use this template and not the new one?

**Comment by rafalp** [comment]
@PROgramJEDI It's no longer available. One would have to implement it themselves through CSS customization.

**Comment by PROgramJEDI** [comment]
> @PROgramJEDI It's no longer available. One would have to implement it themselves through CSS customization.

Can't I find it on past versions?
