### ISSUE TITLE
Change in default subscription option from admin section doesn't bind to newly created user.

### ISSUE THREAD

**Issue by Bindeep** [rafalp/Misago#1345]
@rafalp 

What I have seen is while creating new user attributes like subscribe_to_started_threads, subscribe_to_replied_threads are populated but the instance is not saved to the database.

    def setup_new_user(settings, user)
         set_default_subscription_options(settings, user)

         set_default_avatar(
             user, settings.default_avatar, settings.default_gravatar_fallback
         )

       if user.joined_from_ip:
             create_user_audit_trail(user, user.joined_from_ip, user)

I couldn't find a code where the newly created user instance is saved along with the updated setting.
In the tests also while asserting the value used is not fetched from DB. since the user's attribute is populated and the same user object is used without fetching from the DB test is likely to pass.
Am I missing something?

**Comment by rafalp** [comment]
It's a bug. `set_default_subscription_options` should call `save(update_fields=[...])` on user.

PR welcome. :)
