### ISSUE TITLE
Cannot run tests if I am running the dev website

### ISSUE THREAD

**Issue by bobfang1992** [rafalp/Misago#1363]
Hi, curiously I cannot run the tests if I have the dev website up (via `./dev init && docker-compose up`), this is because the docker image will hold ownership to `./devproject/media` and when running unit test `pytest` will compete with docker for ownership. I am wondering how you solve this problem?

Thanks!

**Comment by rafalp** [comment]
I stop the site via `docker-compose stop` then run tests using the `./dev test` shortcut.

I've never had a need to have dev site up when running tests.
