### ISSUE TITLE
Login and registration broken on new install

### ISSUE THREAD

**Issue by vincenzoromeo** [rafalp/Misago#1364]
I'm running a fresh install from GitHub `master`, no Docker and all that jazz. Everything is working fine, I can post threads, create categories, do all the things, etc.

But when I click on the Sign In and/or Register button some javascript fails and it looks to do with social auth:
```javascript
Uncaught TypeError: Cannot read property 'length' of undefined
    at a (misago.js? [sm]:112)
    at l._constructComponentWithoutOwner (vendor.js? [sm]:22549)
    at l._constructComponent (vendor.js? [sm]:22525)
    at l.mountComponent (vendor.js? [sm]:22428)
    at Object.mountComponent (vendor.js? [sm]:28715)
    at X.mountChildren (vendor.js? [sm]:28119)
    at X._createInitialChildren (vendor.js? [sm]:23951)
    at X.mountComponent (vendor.js? [sm]:23770)
    at Object.mountComponent (vendor.js? [sm]:28715)
    at X.mountChildren (vendor.js? [sm]:28119)
```

Looking at line 112 of misago.js I see this line: 
```javascript
if (socialAuth.length === 0) return null;
```
For whatever reason `socialAuth` isn't defined and so calling `.length` on it raises the exception and breaks the Sign In functionality.

Why might that var not be set? Am I missing a setting in the backend? I don't actually want any social auth login as I'm just running the server in test mode and want to let my users register without email registration.

**Comment by rafalp** [comment]
`socialAuth` is taken from [here](https://github.com/rafalp/Misago/blob/master/misago/socialauth/context_processors.py). It should be rendered within Misago's HTML as `"SOCIAL_AUTH": []`. Is this the case for your site?

**Comment by vincenzoromeo** [comment]
It is blank in my installation.

Is it expected behaviour for it to be null if no social auth providers are enabled? My expectation was that users could register and sign in without social auth providers being enabled in the admin control panel.

**Comment by vincenzoromeo** [comment]
disregard!

I found the problem `misago.socialauth.context_processors.preload_socialauth_json` was disabled in my settings.py

how embarassing..
