### ISSUE TITLE
Is pytza unused dependency?

### ISSUE THREAD

**Issue by suliuzh** [rafalp/Misago#1367]
Hi,
There seems to be no code in the source code that uses "pytz". But in “requirements.txt”, "pytz==2020.1" is still listed.
The following commit removes "import pytz" in "misago/users/middleware.py ".
[fix #740....](https://github.com/rafalp/Misago/commit/be5bb6a97f325f12af4bac0d7528b03927c2b160#diff-56f5a0c096c53da2b81e092a4b00f22f1509b9babf5696ee01dcd9c648940d91)
So is pytz a unused dependency?

**Comment by rafalp** [comment]
`pytz` is timezones database that Django uses for timezone conversion.
