### ISSUE TITLE
前端怎么启动

### ISSUE THREAD

**Issue by lijin90** [rafalp/Misago#1370]
里面的前端怎么启动，需要下载什么插件或者配置文件吗

**Comment by mr-ant** [comment]
本地开发要用到 npm。部署服务器用作者的另一个库 misago-docker。

**Comment by lijin90** [comment]
npm install 了，gulp也安装了，启动命令是什么，package.json里面的启动命令执行一直不行，现在只是想单独启动前端

**Comment by Jiansiyu** [comment]
I do it like this:


*  change the devproject, make sure it have the correct database setting
*  create virtual env and install all the requirements 
*  in virtual env run ```python manage.py startserver```

Hope this will help
