### ISSUE TITLE
Release to PyPi using Github CI

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#1379]

**Comment by justinmayer** [comment]
I would be happy to assist with automating Misago PyPI releases via GitHub Actions and [AutoPub](https://justinmayer.com/projects/autopub/), a tool I created explicitly to facilitate this endeavor.

@rafalp: Just so I know whether I should submit a pull request, would you please let me know if you are interested in my assistance with this effort?

**Comment by rafalp** [comment]
Hey, I was considering using the pre-made workflow that publishes new release on git tag, basically [this](https://github.com/mirumee/ariadne/blob/main/.github/workflows/publish.yml).

Main way Misago is deployed is with `misago-docker`, and starting with v4 Misago will be installed in docker through git module and not PYPI, with separate modules for client and admin dashboard. So we would need automation for both this repo and misago-docker I guess?
