### ISSUE TITLE
Usage with Vercel!

### ISSUE THREAD

**Issue by dekrypted** [rafalp/Misago#1390]
Hello! Nice work on this, it's an awesome BB!
May I ask, is it possible to use it with [Vercel?](https://vercel.com)

Thank you!

**Comment by rafalp** [comment]
@dekrypted Hi, did you find the answer?

**Comment by dekrypted** [comment]
> @dekrypted Hi, did you find the answer?

No, I did not. However it's no longer needed (I'm getting a VPS)
Thank you anyway, this is an awesome software and I can't wait to try it out!
