### ISSUE TITLE
Analytics?

### ISSUE THREAD

**Issue by wojtekxtx** [rafalp/Misago#1392]
What the fucking fuck?????????????

[This file](misago/admin/src/analytics.js) WHAT THE FUCK ???????????????

Never will I use `misago` with analytics!

No wonder this repo is so sparsely commited to!

**Comment by rafalp** [comment]
@wojtekxtx Protip from one dev to another: don't drop the f-bombs, be an ass or insult other people work over the things you don't understand.

Your link is broken so I take it you mean [analytics.js](https://github.com/rafalp/Misago/blob/master/misago/admin/src/analytics.js) from Misago's admin.

This file is a React.JS component that pulls forum analytics from it's GraphQL API and displays charts with those data on forum admin dashboard:

![Zrzut ekranu 2022-09-30 o 17 05 54](https://user-images.githubusercontent.com/750553/193300002-71bf0be9-83db-4995-8f06-7f6c402feda1.png)

**Comment by wojtekxtx** [comment]
>  things you don't understand.

Problem is: I do understand.

Doesnt matter how its used or what its used for: analytics is strictly what it sounds: **gathering data**. Whats done with gathered data later on is whole another issue.

**Comment by rafalp** [comment]
@wojtekxtx No, you obviously don't understand.

> gathering data
> Whats done with gathered data later on is whole another issue.

Please show how this data is gathered and why is it gathered wrong. So far you have only insulted me three times and didn't display real concerns. You are only making drama because word "analytics" is used.

**Comment by wojtekxtx** [comment]
Oh c'mon: gathered by the way THAT ITS STORED IN `DB` AND LATER RETRIEVED.

**Comment by rafalp** [comment]
@wojtekxtx ok, and where is internet forum software supposed to store user accounts, categories, threads, posts and attachments, if storing those in database and later retrieval is malicious?

**Comment by rafalp** [comment]
Funny thing is, **analytics is really nothing to do with gathering data**, it's just **analyzing** data which is already there. Google just muddied the water by calling the data gathering part analytics too.

Those analytics Misago do, are simple database selects from what's already there in database, aggregated by date of creation. This is nothing that any other software out there does, be it forum, ecommerce or other.

**Comment by wojtekxtx** [comment]
> Google just muddied the water by calling the data gathering part analytics too.

Google just **restated well known fact**.

> Those analytics Misago do, are simple database selects from what's already there in database, aggregated by date of creation.

True, Ive analyzed the code behind. But, questions still stand:

* why your product gathers data like how many times user did something?
* Is this data crucial to day-to-day operation of the platform?
* if data like this is bewing collected, than why not collect other user data ( more sensitive one )?

**Comment by rafalp** [comment]
> True, Ive analyzed the code behind. But, questions still stand:

You shoud've analyzed the code before dropping the F-bombs and insulting somebody's work.

> why your product gathers data like how many times user did something?
> why your product gathers data like how many times user did something?
> Is this data crucial to day-to-day operation of the platform?

This is not a product, I'm not a company. It's an open source project done in free time and made available to others in hopes it will be useful to them.

I've did a glimpse on your github profile and I see that you are researching internet forum software. Are you really asking why forums count user's threads/posts and such? They do it to display that data on user profile, to let other users a glimpse on how active user they are dealing with is.

Here's XenForo:

<img width="424" alt="Zrzut ekranu 2022-09-30 o 20 11 18" src="https://user-images.githubusercontent.com/750553/193331430-ce6fb6ec-9572-421b-9576-6f4b8402e79b.png">

Here's Discourse:

<img width="1066" alt="Zrzut ekranu 2022-09-30 o 20 12 52" src="https://user-images.githubusercontent.com/750553/193331594-7b721076-6709-4663-bf61-5b58dd68ed44.png">

> if data like this is bewing collected, than why not collect other user data ( more sensitive one )?

You are being dishonest in this question, trying to provoke slippery slope argument. Nuh-uh.

**Comment by wojtekxtx** [comment]
> This is not a product,

Good joke; you ( doesnt matter if you personally or with a company ) created it, so yes, it **IS** a product ( of your work ).

> Are you really asking why forums count user's threads/posts and such?

You either:
* trying to provoke me,
* seriously dont follow this discussion........

> They do it to display that data **on user profile**

Is admin dashboard a user profile?

**Comment by rafalp** [comment]
Yeah, this discussion has ran its course. Not ever once you've attempted to display a good will here or attempt to be reasonable, so I'm done spending time on this.
