### ISSUE TITLE
Tests fail when LANGUAGE_CODE not "en-us"

### ISSUE THREAD

**Issue by alff0x1f** [rafalp/Misago#1426]
### Steps to reproduce:
1) Run local development version (master branch, bc086c47d6f5645379b9e8d0ed17aecd3fce24e9)
2) Change `LANGUAGE_CODE `in `devproject/settings.py`
3) run `pytest -x`

> misago/admin/tests/test_404_view.py:8: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> 
> response = <HttpResponse status_code=404, "text/html; charset=utf-8">, string = 'Administration', status_code = 404
> 
>     def assert_contains(response, string, status_code=200):
>         assert response.status_code == status_code
>         fail_message = f'"{string}" not found in response.content'
>         assert string in response.content.decode("utf-8"), fail_message
> E       AssertionError: "Administration" not found in response.content

### Possible solution:
Add hardcoded i18n to `test_settings.py`

    LANGUAGE_CODE = "en-us"

**Comment by rafalp** [comment]
This is perfect material for a PR ;)

**Comment by alff0x1f** [comment]
Ok, I make it

**Comment by rafalp** [comment]
Fixed on master, will ship in 0.28, thank you!
