### ISSUE TITLE
Display admin control panel link in user menu for admins

### ISSUE THREAD

**Issue by CyberFox001** [rafalp/Misago#1445]
Hello,

First, thank you for this amazing application. :)

I recently deployed an instance of Misago. But I can't found, in the documentation, what is the URL for the  Admin control panel. I had to look in the source code of the app.

Did I miss it or did it miss in the documentation ?

**Comment by rafalp** [comment]
Hey,

It's documented at the end of setup guide, after Docker images were started:

<img width="850" alt="Zrzut ekranu 2023-01-28 o 23 51 09" src="https://user-images.githubusercontent.com/750553/215294706-cb4f3f3c-ed6e-4018-bc61-e51be5c871bb.png">

But I guess we could expose it in user menu when user is admin and there's setting for this.

**Comment by CyberFox001** [comment]
Ho, thanks.

> It's documented at the end of setup guide, after Docker images were started:

Ah, my bad, I skipped this part. As this part document the usage of `misago_docker`, and I didn't really use  `misago_docker`, I didn't think to read it. :(

> But I guess we could expose it in user menu when user is admin and there's setting for this.

It would be nice. :)

**Comment by olivatooo** [comment]
Found the admin panel thanks to this issue!
