### ISSUE TITLE
Pagination for Categories in both frontend and backend

### ISSUE THREAD

**Issue by thepukar** [rafalp/Misago#1456]
It's better to add pagination for categories, in both frontend and backend. It will help if there are many categories.

**Comment by rafalp** [comment]
How many categories do you have?

**Comment by thepukar** [comment]
Currently, more than 50.

**Comment by rafalp** [comment]
I don't think pagination for categories will ever happen. It takes completely different UI and UX design on forum to support hundreds of categories.
