### ISSUE TITLE
Don't ask user about discarding message/losing changes if they haven't done anything in editor

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#1540]

**Comment by manuel12** [comment]
Hello, I would like to try this to fix this issue, if that's ok.

**Comment by rafalp** [comment]
Hi, you are welcome to try but please beware that Misago’s JavaScript is very hacky and incorrect React 15. I am still more than happy to help you if you want to still try contributing here :)

**Comment by manuel12** [comment]
@rafalp No problem, I will give it a try! :)

**Comment by manuel12** [comment]
@rafalp I've managed to remove the 'Are you sure you want to discard...' dialog in  threads, edits and replies. I see that there  are also dialogs in polls, but I'm not sure how to create one, can you tell how to create a poll?

**Comment by rafalp** [comment]
If it helps, you may instead try contributing a PR that updates react.js to latest 16.x version first, because that will allow for the use of react fragments, new context API and hooks while keeping backwards compat.

**Comment by manuel12** [comment]
> If it helps, you may instead try contributing a PR that updates react.js to latest 16.x version first, because that will allow for the use of react fragments, new context API and hooks while keeping backwards compat.

I can try to make another PR about this version issues next.

**Comment by rafalp** [comment]
> I can try to make another PR about this version issues next.

I've added a task for this to the roadmap: https://github.com/rafalp/Misago/issues/1635
