### ISSUE TITLE
Private thread permissions fails to restrict users

### ISSUE THREAD

**Issue by nfeddema** [rafalp/Misago#1630]
Suppose a "member" user has the following (default) permissions:

- Can use private threads: No
- Can start private threads: No
- Max number of users invited to private thread: 3

This user will still be able to use private threads and start private threads.

Further, they will be limited to 3 "users invited" even if I set "Max number of users..." to 2 or 1.  Numbers greater than 3 work correctly.

(Thanks for all your work on this great project!)

**Comment by rafalp** [comment]
This sounds like this user has more than one role, so even when you take away those permissions from them, other permission set still grants them private threads access.

**Comment by nfeddema** [comment]
No, I just tried again to make sure.  I made a new user and immediately created a private thread with that user.  I then went into the Admin to make sure that the user was assigned _only_ to the "Member" role, and that the "Member" role is using the permissions defined above.  The new user should not have been able to make a new private thread given his permissions.

I am using Misago default settings.  I have only created two users and run your "fakedata" script.  I am one commit behind your main branch, which was updated 15 hours ago.

**Comment by rafalp** [comment]
<img width="401" alt="Zrzut ekranu 2023-06-11 o 14 08 29" src="https://github.com/rafalp/Misago/assets/750553/8db72d51-478b-4ac9-8a5a-ba39d9af7f7b">

Remember that user permissions come from both their roles and ranks. "Member" rank includes "Private threads" permission set.

**Comment by rafalp** [comment]
To be fair, this permission system is confusing and I am already planning to change it.

See #1386 for more details.

**Comment by nfeddema** [comment]
Ah, you are right!  Sorry about that.
