### ISSUE TITLE
Update React.js and react-router to latest backward-compatible versions

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#1635]
Currently Misago uses React 15.7 and React Router 2.8.

This means following goodies are not available:

- Fragments
- "New" contexts API
- Hooks

Updating all dependencies to latest versions in one PR is a massive task. I've [tried](https://github.com/rafalp/Misago/pull/1534) this but had to stop this to prioritize other work.

Plan B is to take small steps approach to updating the UI code. React 16.8 implements all the above things and claims to be backwards compatible with 15.7, so we should try doing that. And while at it we should also try updating React Router to version 3 or 4 if differences between those are not large (like how they are in v5 and v6).

**Comment by manuel12** [comment]
@rafalp This seems to not only be massive but could cause issues that might not be immediately apparent in many parts of the application.

What do you think about having some automated end-to-end tests in place first? This way we make sure most important functionality is working, and then start to update the different parts of the app. This way it would be possible to see if some parts of the application broke without having to go through excessive manual testing.

I have experience creating end-to-end test suites with Cypress. Tell me if you are interested and I can make some a smoke testing suite for the most important functionality. Once we have this  then we can update the versions with the security of what is working and what is not.

**Comment by rafalp** [comment]
> What do you think about having some automated end-to-end tests in place first?

I feel that implementing those is going to take more time than testing the changes by hand after they are implemented. If I've had time for those, I wouldn't be looking for faster option but would do full rewrite of whole UI anyway.

Another argument against tests is that in late 2024 I would in fact like to start writing new UI for Misago from mostly scratch, using Typescript, modern React and either tRPC or custom RPC API. But Misago's user out there can't wait few years stuck with current crappy UI so I am desperate for any half measure that will let me use at least some of modern react's features in meantime.
