### ISSUE TITLE
Add "Sign in with Discord" option

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#1637]
Misago already implements bunch of 3rd party sign in options, but there's no Discord option in here.

While I have other priorities preventing me from implementing this myself, people familiar with Django should have no problem just copying other integration existing in Misago and changing it to Discord. Under the hood all integrations are based on Django Social Auth anyway, so this task would include:

- Adding new provider to [providers list](https://github.com/rafalp/Misago/blob/main/misago/socialauth/apps.py).
- Adding [admin form](https://github.com/rafalp/Misago/tree/main/misago/socialauth/admin/forms)
- Adding [admin form template](https://github.com/rafalp/Misago/tree/main/misago/templates/misago/admin/socialauth)

**Comment by vikramlance** [comment]
@rafalp I can work on this issue.

**Comment by rafalp** [comment]
Thank you! I'll assign you to it. If you have any questions, please ask here or on discord.
