### ISSUE TITLE
Python 3.5 support

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#309]
Todo:

* [x] **Setup test build on Travis CI**
* [x] **Tests passing on Py 3.5**

**Comment by Braintelligence** [comment]
Very interested in seeing Python 3+ support here.
Right now there is only Misago or using some kind of user-login-forum-bridge for me.

I really do want to use Misago, though!

**Comment by rafalp** [comment]
It is going to happen, but currently I reaching feature completion much higher priority for me.

**Comment by NotKit** [comment]
I've started working on this. Got frontend/admin pages rendering on Python 3.5. Now need to make sure tests are still passing. The changes list is not large, however it would require updating to newer Django (and other dependenices) version.

**Comment by Braintelligence** [comment]
Sadly I already moved on and will code a bridge for Flarum in the near future. Wish you the best of luck.

**Comment by rafalp** [comment]
@NotKit 

Woohoo, thats really amazing!

I've planned to bump tests coverage first to be calmer about possible crashes slipping by the deps/py bump, but its okay.

I think only real problem with deps update are changes in model initialization in Django after 1.7 that make Misago crash on init. Everything else can be dealt with by slowly tackling warnings later on.

When I wrap up current work on threads lists (only threads moderation on todo, most likely I'll close it before month's end), I'll look into deps bump and tests coverage to open the path for you to push this further.

In meantime could you please keep on doing your amazing thing pushing py3.5k support and maybe look into travis config to see if you could make it run against python 3.5 in adition to 2.7? If not I'll take care of it myself, but gotta wrap up threads moderation first.


@Braintelligence 

It's ok. Don't wait for software releases, always decide on what's available here and now, or you risk being stuck waiting for something that'll never release or will disappoint your expetations after delivery.

Thanks!

**Comment by NotKit** [comment]
@rafalp All right, I will try to do what you asked with travis. For some reason I didn't experience crashes with Django 1.9.6 on Python 3.5, maybe it's fixed upstream already or happens only on Python 2.7, will check later.

**Comment by rafalp** [comment]
@NotKit could you please update us on the state of your efforts? I've closed threads lists milestone on the weekend and I could help you out with setting up Travis to run against both 2.7 and 3.5 as well as bumping deps to latest before moving on to thread view/posting milestone.

**Comment by rafalp** [comment]
@NotKit Django's 1.9 is LTS, isnt it? I think its safest bet to stick to it until before release, unless 1.10 has features for compatibility with with 3.5 that 1.9 lacks.

Btw, as contributor could you hop on the Gitter?

**Comment by rafalp** [comment]
And its done, thank you, @NotKit !
