### ISSUE TITLE
Multiple quotes in one reply

### ISSUE THREAD

**Issue by dsociative** [rafalp/Misago#339]
Now reply button quotes one message
![quotes_button](https://cloud.githubusercontent.com/assets/56024/2535046/add2fda0-b587-11e3-9404-2945953d006a.jpg)
![result](https://cloud.githubusercontent.com/assets/56024/2535110/16803dd0-b589-11e3-9cfa-42696078af4a.png)

I want to quote many users in single post, instead of only one as it realized now. 
Think to add a quote in the quick response will be better
![result2](https://cloud.githubusercontent.com/assets/56024/2535203/b2d2c6ca-b58a-11e3-8d5c-ebefb86b32b6.png)

**Comment by rafalp** [comment]
Marking this for A1.
