### ISSUE TITLE
Integrations with existing sites

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#415]
Top feature request of all time for Misago is easy integration with existing sites. While my original plan was to try make Misago easier to integrate with existing Django projects, after much exploration on the matter I have concluded that doing so would be a mistake, resulting solution being nightmare to maintain while at same time not making integrations easy at all for others.

Instead Misago will implement features enabling it to be configured to use cookie with JWT set by your site as well as to redirect users to your login/registration forms, as well as expose you additional API endpoint to forcefully update user from your own application if you wish so.

### TODO

- Authentication backend that would create/sync/sign user in based on JWT from cookie
- Check JTI claim before creating/syncing user to JWT
- Make login/reset password/register/logout options in menu redirect to 3rd party site
- Disable register API
- Disable email/password/username change options in user panel
- Optionally disable avatar options if Misago is configured to use avatar from JWT
- Still provide avatar/username moderation in case its needed
- Provide means to force-logout user or invalidate their tokens if they are doing re-play attack

**Comment by sirex** [comment]
Is this task about implementing OpenID/OAuth support?

**Comment by rafalp** [comment]
@sirex nope, sign in with OpenID/OAuth is the #416 thats currently underway to land in Misago 0.18

**Comment by yeisonvargasf** [comment]
Hi @rafalp, is there any progress with this issue? How could I help?

**Comment by rafalp** [comment]
No progress, but if you want to help, you can start with creating PR that would create user account and log them in if they had cookie with valid JWT token, and weren't logged in already. There is Python library called PyJWT that allows easy validation/unpacking of the JWT tokens.

**Comment by yeisonvargasf** [comment]
Yes, I used PyJWT. ok, thanks I will try to work in this the next week.
