### ISSUE TITLE
Docker setup for use in production

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#430]
This container would likely use docker-compose and come with:

- PostgreSQL
- UWSGI
- Nginx
- Memcached or Redis
- Cron
- Volumes for persistent storage

I'm unsure if it should bring the Supervisord to keep things alive or not.

**Comment by rafalp** [comment]
Maintaining this would be huge burden, plus Misago's dependencies are small in scale and easy to setup oneself using one of many example django images provided by say, digital ocean or heroku.

**Comment by kissgyorgy** [comment]
I will do it for you! Please reopen this issue. Docker is so mainstream today and so easy to get started it is well worth it.

**Comment by rafalp** [comment]
@kissgyorgy I would like to see this image as separate repo, alike to what Discourse does:

https://github.com/discourse/discourse_docker

**Comment by einarf** [comment]
I'll see if I can take a stab at this one slowly as a side project. Already started on a setup at https://github.com/einarf/misago-docker, but this will probably need a very different approach.

The misago container itself should start and configure the project when building the image so you in theory can just do `docker-compose up -d` and have a working setup within a few seconds.

**Comment by rafalp** [comment]
I would like to have repo that will contain:

1. Misago project already setup for you, named `misagodocker` with all directories and files that creating new misago project setups for you.
2. Docker compose setting up PostgreSQL 10, memcached, misago with uwsgi, nginx and volumes for those.
3. Config files for uwsgi and nginx in repos main directory.
4. Perhaps `env_file` like `misagodocker.env` in main dir too for user to fill in blanks.
5. Readme explaining what stuff needs to be filled in `env_file` and nginx's config (eg. fill in `SECRET_KEY=` with stuff from [this secret key generator](https://www.miniwebtool.com/django-secret-key-generator/), go to nginx config and replace yoursite.com with your domain).

**Comment by einarf** [comment]
OK, so you want to `misagodocker` project to actually be present in the repo itself? I guess that makes it a lot more flexible as you can tweak staticfiles and such. That means the `misagodocker` project needs to be recreated for every release. That would probably be the case anyway, so more than acceptable.

When it comes to versions we could create a branch for each release (moved to tags eventually)

**Comment by einarf** [comment]
These are also interesting as it makes the reverse proxy and possibly certificate setup very nice and clean:

https://github.com/jwilder/nginx-proxy
https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion

**Comment by rafalp** [comment]
Docker setup for use on production is now available here: https://github.com/rafalp/misago_docker
