### ISSUE TITLE
Translation informal/formal

### ISSUE THREAD

**Issue by ottk3** [rafalp/Misago#503]
Hi, I started working on the german translation for the Misago project. Since the translation is based on the `locale` there's only one translation per language. That's a problem with the german translation because informal/formal variants are very common depending on the use of the forums.

Eg. *You* might be *Du* (informal) or *Sie* (formal). You should consider a way to allow multiple translations for one locale.

**Comment by rafalp** [comment]
I am not sure what you are asking for? Is this organization request? If so, I don't mind different translations for one locale existing at same time.

If its request for adding some sort of "official/unofficial" toggle in settings, that's not going to happen, but thou shall not despair, for Django has mechanic for overriding translations:

https://docs.djangoproject.com/en/1.7/topics/i18n/translation/#how-django-discovers-translations

Ergo you could create custom translations directory, throw in alternative translation there, and add it on the top of `LOCALE_PATHS`, so it gets loaded before shipped one.

**Comment by ottk3** [comment]
Okay, then should the "official" be formal or informal?

**Comment by rafalp** [comment]
To be honest, I am not interested nor willing to make that decision. In fact I know there are already languages out there that autors will love to argue that XYZ is less/more formal than YZX and should be changed in translation YYZ. I have experienced that already in different project. ;)

I can only say that while I am not really considering Misago software for ties, and so original locale is walking the line between those two. See error 500 message for example:

    <h1>Something's broken...</h1>
    <p class="lead">The page you have requested is currently unavailable due to an error.</p>
    <p class="lead">The problem may be temporary, so please wait few seconds and try refreshing page. If this doesn't help, please visit us later.</p>
    <p class="lead">Thank you for your patience.</p>

**Comment by rafalp** [comment]
As for picking official translation, I guess first come, first serve will be approach used, but if we want folk to use "official" transifex for that, we'll better write contribution terms laying out certain conditions and rules for those willing to. Prolly cession of copyrights to translations from their authors.
