### ISSUE TITLE
Generated app has the wrong requirement

### ISSUE THREAD

**Issue by kxxoling** [rafalp/Misago#533]
0. Forgot to add recaptcha-client
1. markdown==2.4.1 : It changed its API and caused some compatible error, should still use markdown 2.3 as the bbs suggested.

**Comment by kxxoling** [comment]
And something strange: Misago requires Django 1.6, but the generated app requires django 1.7.6.

**Comment by rafalp** [comment]
Nothing strange really. Code on master is next big release for Misago that I'm aiming to Django 1.8 ultimately, while code from releases still requires 1.6 due to me not having much time to for "real" maintenace work.

Parser's tests are passing for markdown 2.4.1 on master, so its non-issue imho. :]

**Comment by kxxoling** [comment]
Um... Saw it. Seems v o.6 would be much different from v 0.5, would them be compatible? If I build a site with v 0.5, how could I upgrade it when the v 0.6 released?

Also, I'm interested in building app the v 0.6 way. Is there any tutorial now?

**Comment by rafalp** [comment]
There's massive compatibility break between 0.5 and 0.6, but one such break already happened in project's history, around 0.2 or 0.3 releases AFAIR. Last time I've provided data migration tool that allowed you to move data from old forum to new one.

I'm also [documenting](http://misago.readthedocs.org/en/latest/) 0.6 for those interested in extending it, but this halway trough this release "lets roll in ember UI" change happened that made few parts of doc's void (namely extending users lists, profiles, user control panel and posting),

**Comment by kxxoling** [comment]
The using of 0.6 fits my taste more, but did not figure out how to start with it. Is any example of building a site like the official Misago Forum?

**Comment by rafalp** [comment]
I dunno if 0.6 is complete enough for „starting with”. As it is now its possible to register, change forgotten password, register, change profile settings and see legal pages, but thats it for now (with user lists coming this week hopefully and profiles following by end of the month).

**Comment by kxxoling** [comment]
Seams, it takes a lot of time till now, any help needed? I'm eager with the Forum and Thread functionality!
