### ISSUE TITLE
Migrate from LESS to SASS

### ISSUE THREAD

**Issue by sirex** [rafalp/Misago#534]
Currently Misago has huge Node.js dependency to be able to compile LESS styles. SASS has [libsas](https://pypi.python.org/pypi/libsass) - that integrates well into Python infrastructure, you just need to `pip install libsass` to make it available.

What your thoughts about it?

**Comment by rafalp** [comment]
Non-issue IMHO as starting with 0.6 Misago has to use build process providen by ember-cli for our assets anyway.

**Comment by sirex** [comment]
@rafalp ember-cli is going to replace django-pipeline?

**Comment by sirex** [comment]
My argument for moving away from Node.js dependency is that Misago should be very easy to deploy. And Node.js is completely different stack with its own package manager and issues. So I would suggest to avoid this if possible making deployment and maintenance easier.

**Comment by rafalp** [comment]
0.6 moves assets build step from deployment to releses due to requirement on special build process on Ember’s part, thus dropping need for either asset pipeline in Django or node.js on deployment server.
