### ISSUE TITLE
Materialize UI

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#538]
* [x] Buttons
* [x] Dropdowns
* [x] Navbar
* [x] Sidenav
* [x] Forms
* [x] Footer
* [x] Modal

**Comment by win32re** [comment]
I'm so excited for version 0.6 :smile:

**Comment by rafalp** [comment]
Ain't gonna be "real" material design, just closer or looser similiarity to it, still i'm fan of shadows over borders <3

**Comment by rafalp** [comment]
Here's quick preview of navbar and new button styles:

![zrzut ekranu 2015-07-15 o 23 02 09](https://cloud.githubusercontent.com/assets/750553/8709851/c0a2f95a-2b45-11e5-9c08-27d5352e5e10.png)

**Comment by win32re** [comment]
Wow, I like it!

**Comment by rafalp** [comment]
![zrzut ekranu 2015-07-19 o 04 16 25](https://cloud.githubusercontent.com/assets/750553/8764253/1f2f6fb0-2dcd-11e5-9094-007598b0be7f.png)

Only modals and footer left to do.

This isn't going to be 100% to the letter with Material spec however, but once Google's Material Design Lite implements missing features (dropdowns, modals, media lists), I may consider switching UI framework.

**Comment by win32re** [comment]
It looks really nice :) I'll definitely use Misago for my next project.

**Comment by liuzheng712** [comment]
This is a awesome job!
But for me, I can't run 0.5.x and master branch, what a pity....
So now , I want join you guys.
The 0.5.x seems a really mess.
And the version about python package and Django make me crazily.
 What a awesome work!

**Comment by rafalp** [comment]
Huh? This aint closed yet? Allrite then :]

![zrzut ekranu 2015-07-26 o 04 28 13](https://cloud.githubusercontent.com/assets/750553/8892273/42113e5e-3350-11e5-9687-48602327f87d.png)
![zrzut ekranu 2015-07-26 o 04 31 28](https://cloud.githubusercontent.com/assets/750553/8892274/422f1050-3350-11e5-9741-55b15eaaf7d4.png)
