### ISSUE TITLE
Reddit-like site hierarchy

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#541]

**Comment by qmgr** [comment]
+1

I recently started a project and I'd like to use Misago 0.6.

1. Is there an approximate date of 0.6 release?
2. Am I going to be able to update Misago 0.6 to 1.0 when it's released?
3. Is there any way I can externally authenticate to Misago from an app using CURL and later on validate the session using a session token?

**Comment by rafalp** [comment]
Not a questions for github issue. Use project forums instead. :]

**Comment by qmgr** [comment]
Okay, thanks :)

**Comment by rafalp** [comment]
Misago 0.6 drops forums and redirections, leaving only categories. This means that every thread belongs to category. There's no way to add forum that acts as redirection, and theres no "forums" and "categories" segregation.

Forum's landing page is list of all threads accessible by you with two sets of filters:

* all threads in current category
* my threads in current category
* new threads in current category
* unread threads in current category
* subscribed threads in current category

Then there is two ways to let you navigate down the categories tree. First, you may click category's name displayed in the "direct subcategories" list. Second, by clicking the "category" label by the thread on list.

Categories are handled in way similar to one that Reddit handles subreddits. Consider such categories tree:

```
+ Threads
  + Games
    + Space Games
```

If you are on forums landing page and there's thread in Space Games, it will show to you badge to "Games" category. If you are in "Games" category, thread will display its real badge, "Space Games". I'm still thinking about displaying bottom category in addition to top one for cases when you don't want to walk the whole path.

There's also page that displays categories list, and setting that lets you switch those two, making categories list landing page. Categories list is also an React.js component mounted within specified container on page, which leaves you a lot of leeway in the matter of expanding categories list with extra information, meaning that **with few custom template-blocks you may make your forum's index page much more familiar to one known from 0.5**.

Obviously threads are far more complex feature-wise than user profiles were, meaning that new features will land less frequently than previous features did. My current focus is on threads lists, where I am currently busy deciding on final looks as well as pushing forward with implementation, adding tests for cases and making codebase easier to support both threads and private threads as well as static views and API endpoint that will back React.js's components responsive for loading more threads, displaying "there are new posts! click here to update threads list!", as well as marking category read and ultimatelly handle moderation.
