### ISSUE TITLE
Add recaptcha-client to requirements.txt

### ISSUE THREAD

**Issue by alff0x1f** [rafalp/Misago#542]
I start follow instructions for install 0.6 to local environment.
 ...
    python setup.py install
    misago-start.py testforum
   pip install -r requirements.txt
 ...

Then I get error, unknown module **recaptcha-client**

I think testforum/requirements.txt must have additional requirement. Possible forum also use recaptcha-client, but this line missed. Thanks!

**Comment by rafalp** [comment]
Nice catch!
