### ISSUE TITLE
0.6 MVP Features

### ISSUE THREAD

**Issue by rafalp** [rafalp/Misago#543]
Until now I was following "from roots" methodology where I was implementing features in order of how many dependencies on other features they have. Ergo a lot of features required ACL that didn't require anything else, so it was implemented first. Threads required users which required auth, so auth was implemented, then users lists (that required users but themselves were required by profiles) and finally profiles. In addition to this great deal of energy was spent on finalising feature before moving on to next one, meaning that user profile completion would mean completion of on-line tracking, following/ignoring and moderation tools for those profiles.

This approach has three big issues that hurt the project in the long run: It delays the time when MVP is achieved and thus delays the time when framework for contributors to work within is laid out and when initial feedback is available.

The new approach is to focus on delivering the MVP as soon as it is possible, with MVP implementing auth flow and basic discussions with stubs for features that discussions depend on. Once MVP is complete, project forums will be migrated to it and updated frequently to be as close to master as possible, demoing state of the project and opening it for early feedback.

## Auth flow
  - [x] Login/Logout
  - [x] Register new account
  - [x] Auth state synced across tabs
  - [x] Reset forgotten password
  - [x] Activate account
  - [x] Resend activation e-mail
  - [x] Switch static banned page with React.js component

## User CP stub
  - [x] Change forum options
  - [x] Change username
  - [x] Change sign-in data

## Change avatar
  - [x] Set generated avatar
  - [x] Fetch gravatar
  - [x] Pick avatar from gallery
  - [x] Upload avatar
  - [x] Crop avatar

## Users list
  - [x] Most active users
  - [x] Ranks users

## User profile
  - [x] Threads
  - [x] Posts
  - [x] Followed users
  - [x] Followed by
  - [x] Name history
  - [x] Ban details
  - [x] Nuke user form orbit
  - [x] Moderate user's avatar
  - [x] Moderate user's username
  - [x] Follow/unfollow user

## Categories
  - [x] Rename forums to categories in code and UI, drop forum types
  - [x] Categories list
  - [x] Cats/Threads index toggle

## Threads list
  - [x] Forum/Category views
  - [x] Threads list component
  - [x] Noscript category picker
  - [x] Noscript pagination for crawlers
  - [x] Unapproved list
  - [x] Moderation

## Thread view
  - [x] Basic threadview
  - [x] Goto views
  - [x] Thread moderation
  - [x] Posts moderation
  - [x] Events moderation
  - [x] Attachments
  - [x] Polls
  - [x] Post history
- [x] Likes
  
## Posting
  - [x] Start thread
  - [x] Reply to thread
  - [x] Edit reply
  - [x] Notifications
  - [x] Markup and editor

## Private threads
  - [x] Threads list
  - [x] Thread view
  - [x] Posting

## Search
  - [x] Search users
  - [x] Search threads

**Comment by Oxyrus** [comment]
May I ask why you decided to move to Mithril.js rafalp?

**Comment by rafalp** [comment]
I am yet to write solid goodbye letter to the Ember.js, but this is [closest](https://theadminzone.com/threads/misago-python-and-django-forum-software.114801/page-7#post-1004642) I've did so far.

**Comment by rafalp** [comment]
Updated OP and progress because components are being moved to React.js

**Comment by 5ebastianm** [comment]
Is this list updated and in sync with current progress?

**Comment by rafalp** [comment]
Aye, the list's in sync with master branch.

**Comment by 5ebastianm** [comment]
So much things to do before 0.6 release :(

After 1.0 is released, will we be able to update 0.6 to 1.0?

**Comment by rafalp** [comment]
Dont worry. There's even more than on the list that's already implemented on master, but needs API endpoints/serializers and views refactoring for React UI.

0.6 isn't really that special minus being first with refactored codebase. It'll be followed by 0.7, 0.8, etc, ect. 1.0 is special milestone reserved for when Misago was in a wild long enough and I feel its mostly complete and stable.

**Comment by 5ebastianm** [comment]
Well, I hope it gets finished soon :)

I love Misago. It's just... so good. Like Discourse but without the slow performance and way better design.

**Comment by rafalp** [comment]
Just pushed users lists to master, now onto profiles (last thing before discussions!)

**Comment by SebastianMalek** [comment]
Nice work! You are awesome :)

**Comment by rafalp** [comment]
Profile layout & basic moderation has landed. Now onto tabs that I dont need threads for, and finally threads!

**Comment by rafalp** [comment]
Pushed Py 3.5k support and theme after 0.6 release. So goal is to release 0.6 that has near-complete feature parity with 0.5, hop ships to it, then add new things in future releases, eg. 0.7 may add python 3.5 support, 0.8 may add profile warnings, 0.9 ignores, 0.10 WYSIWYG editor, etc ect...

**Comment by rafalp** [comment]
Ban details, username history, followed and followers lists pushed. Moving on to threads.

**Comment by SebastianMalek** [comment]
Is a JSON API going to be provided in 0.6?

**Comment by rafalp** [comment]
To change app's state you need to use React.js UI that talks to json API (done in Django REST Framework).

**Comment by SebastianMalek** [comment]
So basically, I can get an API but it's going to be the one React.js UI talks to?

**Comment by rafalp** [comment]
P'much, but its going to be extensive anyway.

**Comment by rafalp** [comment]
Categories milestone landed, after small code maintenance I'll be moving on to threads lists.

**Comment by rafalp** [comment]
Dropped some todo's from list. The plan is to reach MVP state and then migrate project forums for tests/demo.

**Comment by rafalp** [comment]
Tiny milestone: start thread, post reply and edit it actions have landed on master. Their frontend implementation will be crude for a while, but its good start.

**Comment by rafalp** [comment]
Trello for Threadview and Posting:

https://trello.com/b/ecHsZ5Zf/misago-threadview-posting

**Comment by rafalp** [comment]
Just two features to go before Alpha is feature-complete 🎉

**Comment by rafalp** [comment]
Just one more feature and...

![its gone!](https://media.tenor.co/images/bee6a1a03fc6068588e88b61d421a956/raw)

Now just cleanups, bugfixes, then data migrator for Misago 0.5, and we can roll! 🎉
