### ISSUE TITLE
No module named embercliredirects ?

### ISSUE THREAD

**Issue by SuperCrunch** [rafalp/Misago#547]
Hi,

when I run ./manage.py runserver, I get: ImportError: No module named embercliredirects. 

This is coming from this middleware:
'misago.core.middleware.embercliredirects.EmberCLIRedirectsMiddleware',

I'm not familiar with ember too much so it is something I am unaware of. Does anyone know how to solve this issue?

**Comment by rafalp** [comment]
'Lo,

Seems weird, as I've removed Ember-CLI utils with JS framework change. Are you sure you cloned latest master?

**Comment by kingctan** [comment]
I meet the same problem. and I comment the middleware, it can run,but only "Test auth blocks" show in browser.

**Comment by rafalp** [comment]
Oh, I see.

Ok, I'll fix it later today whem I'm off the office.

@kingctan: you'll find answer to your question in readme.md ;)

**Comment by kingctan** [comment]
hi, @rafalp, which readme.md ? or readme.rst ? I checked but no update.

**Comment by rafalp** [comment]
Yup. Anyway [this is](https://github.com/rafalp/Misago#dont-use-this-branch-in-production) what I was going at. If you are looking to run forum, use code form 0.5.x branch. If you want to taste next major release, pull master and see how much already there's.

**Comment by rafalp** [comment]
Nailed it with last push
