### ISSUE TITLE
Initial data is not localised on DB creation

### ISSUE THREAD

**Issue by Didan** [rafalp/Misago#583]
branch 0.5.x
Misago\misago\locale\zh_CN\LC_MESSAGES have django.mo
modify /deployment/settings.py
-LANGUAGE_CODE = 'en_US'
+LANGUAGE_CODE = 'zh_CN'
then i execute  manage.py startmisago
i check database,  find all string is en_US not zh_CN

**Comment by rafalp** [comment]
I'll mark this as wont fix for 0.5, but I'll return to it as part of pre-lease wrap up for 0.6 which actually uses Django's data migrations instead of hack over south.

**Comment by rafalp** [comment]
Could you also confirm that data is not localised in interface? Some stuff gets saved in english to DB, but passess trough gettext() when is rendered (eg. ranks, settings groups).

**Comment by Didan** [comment]
yes,  that data of database is not localised in interface when through browser, but others string in python code is localised.

**Comment by rafalp** [comment]
Closing this, I'll setup other ticket for tracking this in 0.6
