### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by KuzeydekiBuyucu** [rafalp/Misago#603]
Like,Dislike,Show Votes are  not in the django.po

Is it possible to translate manually?

**Comment by rafalp** [comment]
It seems that makemessages need to be ran via manage.py instead of django-admin.py to extract translations from Jinja templates.

**Comment by rafalp** [comment]
I've regenerated po file for misago. New one has 12k lang strings to translate and includes templates.

**Comment by rafalp** [comment]
Apparently transifex ate up the translated strings when I've uploaded regenerated po file. Do you guys have sources elsewhere? It may suck if it'll turn out to be irrecovable. :|

**Comment by KuzeydekiBuyucu** [comment]
Fortunately i had got spare
