### ISSUE TITLE
Member Can't Start thread

### ISSUE THREAD

**Issue by thaiopen** [rafalp/Misago#604]
After install  and add user but user can't not start thread. I try to add  User roles > Member > Can use private threads:   but user cant not still  start thread.

**Comment by rafalp** [comment]
Can you please include screenshots of where you are trying to start thread and what error you are getting?

**Comment by thaiopen** [comment]
![selection_001](https://cloud.githubusercontent.com/assets/10235003/18358082/9c6835c2-761d-11e6-87b1-751b63272bb8.png)

I run website  www.sipatechmeetup.com in Thailand. I found misago forum can help me to startup group of people who interest in Cloud and Devopt community Thailand. But I can't enable thread. Could you please tell me how to set permission in order to allow user (as member) to have permission to start threads? I also  both user role and Category roles already.

**Comment by sebastian-malek** [comment]
Um, you'll have to wait for @rafalp but I don't think this branch is ready
for production yet. Maybe that's why you can't do what you are trying to do.

**Comment by rafalp** [comment]
The way code is on master ATM, you should be able to have discussions already, but @sebastian-malek  is right - its still not ready for production. Besides obvious shortcomings like no private threads or search, it also lacks one important feature to run real forum: moderation tools.

Please use 0.5 release instead. You'll find latest one on releases page.

Thanks!
