### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: Error importing debug panel debug_toolbar.panels.timer: "No module named apps"

### ISSUE THREAD

**Issue by thaiopen** [rafalp/Misago#605]
I install from tag 0.5. How to config debug_toolbar in production.
system
nginx  -> uwsgi -> deployment.setting
file: misago_uwsgi.ini

[uwsgi]
chdir=/home/deploy/Misago
module=deployment.wsgi:application
master=True
vacuum=True
max-requests=5000
daemonize=/home/deploy/Misago/tmp/misago.log
home=/home/deploy/venv27
socket=/home/deploy/Misago/tmp/misago.sock
chmod-socket=664
uid=1000
gid=1000

**Comment by rafalp** [comment]
Hey,

Could you please run ``pip list`` and paste here it's output?

**Comment by thaiopen** [comment]
Hi,
source venv27/bin/activate
pip list
beautifulsoup4 (4.4.1)
bleach (1.4.3)
Django (1.5.12)
django-crispy-forms (1.6.0)
django-debug-toolbar (1.0)
django-floppyforms (1.7.0)
django-haystack (2.5.0)
django-htmlmin (0.9.1)
django-jinja (2.2.1)
django-mptt (0.5.5)
djangorestframework (3.3.3)
fake-factory (0.5.9)
html5lib (0.9999999)
ipaddress (1.0.16)
Jinja2 (2.8)
Markdown (2.6.6)
MarkupSafe (0.23)
Misago (0.6a1.dev1)
path.py (8.2.1)
Pillow (3.3.0)
pip (8.1.2)
psycopg2 (2.6.2)
python-dateutil (2.5.3)
pytz (2013b0)
recaptcha-client (1.0.6)
requests (2.10.0)
setuptools (25.1.0)
signals (0.0.2)
six (1.10.0)
South (0.8.4)
sqlparse (0.2.0)
Unidecode (0.4.19)
uWSGI (2.0.13.1)
wheel (0.29.0)
Whoosh (2.5.7)

**Comment by rafalp** [comment]
Please try with Django 1.6 and compatibile debug toolbar.

On side note, this isn't the bug with Misago, so closing as we aren't using github for support tickets. If you have further questions, please use official forums for that.

Thanks!
