### ISSUE TITLE
Upload new avatar picture link

### ISSUE THREAD

**Issue by oscanog** [rafalp/Misago#607]
Good day sir Raf. I'm a fan of your work. I love combining django with react. It's fast and beautiful. I can see that you're currently working on V0.6, i manage to run v0.6, but i can see that it's not finished yet. So i tested lower version which is 0.5.7 everything's seem alright. But there's a problem with changing the avatar. There's no link for it. Advance thanks for d' answer

**Comment by rafalp** [comment]
Can you please go to "Change options" and confirm that that "Change avatar" is not present in menu on the left?

**Comment by oscanog** [comment]
thanks for response
here's the screenshot.
[(http://i.imgur.com/sfLCH4o.jpg)]

unedited "usercp/avatar.html"
line 29

> `  <ul class="unstyled">`
` {% if 'gravatar' in settings.avatars_types and user.avatar_type != 'gravatar' %}<li><form action="{{ url('usercp_avatar_gravatar') }}" method="post" class="form-button"><button type="submit" class="btn btn-link"><i class="icon-share"></i> {% trans %}Use Gravatar{% endtrans %}</button><input type="hidden" name="{{ csrf_id }}" value="{{ csrf_token }}"></form></li>{% endif %}`
`{% if 'gallery' in settings.avatars_types %}<li><a href="{{ url('usercp_avatar_gallery') }}" class="btn btn-link"><i class="icon-th"></i> {% trans %}Pick Avatar from Gallery{% endtrans %}</a></li>{% endif %}`
` {% if user.avatar_type == 'upload' %}<li id="crop-js" style="display: none;"><a href="{{ url('usercp_avatar_crop') }}" class="btn btn-link"><i class="icon-fullscreen"></i> {% trans %}Crop Your Avatar{% endtrans %}</a></li>{% endif %}`
`{% if 'upload' in settings.avatars_types %}<li><a href="{{ url('usercp_avatar_upload') }}" class="btn btn-link"><i class="icon-picture"></i> {% trans %}Upload Avatar{% endtrans %}</a></li>{% endif %}`
`</ul>`

had you experienced this when you're working on v0.5.7?
thanks.

**Comment by oscanog** [comment]
[http://i.imgur.com/3QmqdFG.jpg](url)

It's okay now, somehow, the problem was solved,
My question is.. -> Admin can't change their avatar... True or False?
so only registered members as Users have the function of changing their avatars, right?

**Comment by rafalp** [comment]
You may via admin control panel.

If its fixed I'll close the issue. Please don't use github's issue system for support requests as per readme. I want project forums to be primary source of support information.

Thanks!
