### ISSUE TITLE
CAS support

### ISSUE THREAD

**Issue by ioanb7** [rafalp/Misago#614]
Hi Rafał,

Is there any CAS support in Misago 0.5 or upcoming 0.6?

**Comment by rafalp** [comment]
Nope,

Until 1.0 hits I'll have other priorities that I'll pursue. However seeing how Misago from 0.6 onwards will use Django Auth for users, there could be an app on Django packages that somebody could eventually use to deliver such feature.

**Comment by rafalp** [comment]
Closing as something I don't have interest maintaining within core.

**Comment by ioanb7** [comment]
Hi Rafał,

I've made this a week ago and it seems to work fine. However, I still want to pass it by you before it goes into the master as I had to hack a few things:
* Removing default urls for logging in (url confs and templates)
* Passing random generated password to get_user_model()..objects.create_user because it would accept blank
* Passing 0.0.0.0 as the registration IP because there is no need for Misago to prevent registration hacking - when using CAS
* Removed e-mail validation

I am thinking that it's ok if I just add the code and instructions on how to use in the docs. Making it like a markdown article.

What do you think?

Regards,
Ioan.

**Comment by rafalp** [comment]
> What do you think?

Well, what do you ask? ;)

**Comment by ioanb7** [comment]
Where do you want me to put the code?

**Comment by rafalp** [comment]
Please put it on dedicated branch of your GH's fork. I'll have an look at it then.

**Comment by ioanb7** [comment]
Hi Rafal, give me a week please. I have to travel for a few days and I've got to reinstall what I've got on a different machine. Thanks.

**Comment by ioanb7** [comment]
Hi Rafal,
here is a somewhat (incomplete) tutorial of how to get it working. It seems like a lot of work, but it will be rather easy for those that know what CAS does and how to set it up, as well as those who digged a bit into misago to customise it for their own liking.

Let me know if that's ok.

#Tutorial:

Warning: this tutorial ditches the misago authentication and replaces it with CAS login. CAS is not responsible with registering users, thus you've got to that yourself. This tutorial also ditches the e-mail confirmation, as it is part of the registration part which you'll have to do yourself. E-mail authentication is also replaced with username authentication.
Info: for registration, you can use LDAP and let CAS connect to LDAP. Then, you can create another django app with it's own urls that takes care of introducing raws into LDAP. For this, you can use pyldap. Upon registration, you might want to use recaptcha2. (there are django plugins out there)


##step 1: install and configure your CAS
##step 2: install django dependencies:
pip install django_cas_ng
##step 3: configure misago to connect with CAS
* Go into your app, and start editing settings.py:
* add :
```
INSTALLED_APPS += (
    'django_cas_ng',)

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend', # u can still login with superuser in the admin panel
    'plugins.CASBackend2.CASBackend2'
)

CAS_SERVER_URL = "http://192.168.35.30:8080/cas/"

from django.utils.translation import ugettext_lazy as _
CAS_ADMIN_PREFIX = None
CAS_CREATE_USER = True
CAS_EXTRA_LOGIN_PARAMS = None
CAS_RENEW = False
CAS_IGNORE_REFERER = False
CAS_LOGOUT_COMPLETELY = True
CAS_FORCE_CHANGE_USERNAME_CASE = "lower"
CAS_REDIRECT_URL = '/forum/'
CAS_RETRY_LOGIN = False
CAS_VERSION = '2'
CAS_USERNAME_ATTRIBUTE = 'uid'
CAS_LOGIN_MSG = _("Login succeeded. Welcome, %s.")
CAS_LOGGED_MSG = _("You are logged in as %s.")
CAS_LOGOUT_COMPLETELY = True
CAS_EXTRA_LOGIN_PARAMS = {'renew': True}
```
* create a folder 'plugins' under `yourmisagoapp/' and create the following files: `__init__.py` and `CASBackend2.py`
* leave `__init__.py` empty and add the following to `CASBackend2.py`:
```
"""CAS authentication backend"""
from __future__ import absolute_import
from __future__ import unicode_literals


from django.contrib.auth import authenticate, get_user_model, login
from django.core.exceptions import PermissionDenied
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect

from misago.users.models import ACTIVATION_REQUIRED_ADMIN, ACTIVATION_REQUIRED_USER, ACTIVATION_REQUIRED_NONE

from django.contrib.auth import get_user_model
from django.contrib.auth.backends import ModelBackend
from django.conf import settings

from django_cas_ng.signals import cas_user_authenticated
from django_cas_ng.utils import get_cas_client

User = get_user_model()
#from django.contrib.auth.models import User
__all__ = ['CASBackend2']

import random
import string
def random_word2(length):
    return ''.join([random.choice(string.ascii_letters + string.digits) for n in range(16)])

class CASBackend2(ModelBackend):
    """CAS authentication backend"""

    def authenticate(self, ticket, service, request):
        global settings
        username = ""
        email = random_word2(5) + "@email.email"

        client = get_cas_client(service_url=service)
        username, attributes, pgtiou = client.verify_ticket(ticket)

        if attributes:
            request.session['attributes'] = attributes
        if not username:
            return None

        username_case = settings.CAS_FORCE_CHANGE_USERNAME_CASE
        if username_case == 'lower':
            username = username.lower()
        elif username_case == 'upper':
            username = username.upper()

        try:
            user = User.objects.get(**{User.USERNAME_FIELD: username})
            created = False
        except User.DoesNotExist:
            # check if we want to create new users, if we don't fail auth
            if not settings.CAS_CREATE_USER:
                return None
            # user will have an "unusable" password

            user = User.objects.create_user(
                username,
                email,
                password="npass" + random_word2(5) + "s",
                joined_from_ip="0.0.0.0",  # request.user_ip,
                set_default_avatar=False,
                requires_activation=ACTIVATION_REQUIRED_NONE
            )
            user.save()
            created = True

        if not self.user_can_authenticate(user):
            return None

        if pgtiou and settings.CAS_PROXY_CALLBACK:
            request.session['pgtiou'] = pgtiou

        # send the `cas_user_authenticated` signal
        cas_user_authenticated.send(
            sender=self,
            user=user,
            created=created,
            attributes=attributes,
            ticket=ticket,
            service=service,
        )
        return user

    def user_can_authenticate(self, user):
        return True

    def get_user(self, user_id):
        try:
            return User.objects.get(pk=user_id)
        except User.DoesNotExist:
            return None
```
##step 4: under `yourmisagoapp/urls.py` make sure you've got django_cas_ng at the top of your urls, similar to:
```
import django_cas_ng
from django_cas_ng import views as django_cas_ng_views
urlpatterns = [
    url(r'^forum/accounts/login$', django_cas_ng_views.login),
    url(r'^forum/accounts/logout$', django_cas_ng_views.logout),
```
##Optional steps:
###1: deactivate misago authentication from the frontend (by not including that module)
###2: replace your theme `base.html` or `navbar.html` to delete the old url links and replace with the new ones (you can put them under `yourmisagoapp/theme/templates/misago/base.html' and they will get replaced)

**Comment by ioanb7** [comment]
I am happy to open source my registration app that connects to ldap, once I get e-mail confirmation working - I estimate it will be sometime next week.

**Comment by rafalp** [comment]
I think you'll have best luck by starting repo for your app on github. Will make eventuall code review/feedback possible too. Eg. `random_word2` unobvious name + how it duplicates "get_random_string" that `django.utils` contains. ;)

**Comment by ioanb7** [comment]
Ok, might as well.
For the record, the app will be available here: https://github.com/ioanb7/MisagoCASExample

Ioan
