### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by k0nsl** [rafalp/Misago#617]
I've cloned Misago on one of my VPSes and tried to run `python setup.py install`, but that only yields the following output:
```
error in Misago setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
```
Any ideas?

**Comment by rafalp** [comment]
Guess it's time to set issue template for Misago, eh? ;)

<https://github.com/rafalp/Misago#dont-use-this-branch-in-production>
<https://github.com/rafalp/Misago#bug-reports-features-and-feedback>

Solution for the issue mentioned on project forums:

<http://misago-project.org/thread/initializing-misago-546/#post-1720>
