### ISSUE TITLE
Unable to install Misago

### ISSUE THREAD

**Issue by elcolie** [rafalp/Misago#656]
**Specification:**
commit 3b47b52dbb033b8296e173aa1b577e34aa90f9c4
Author: Rafa<C5><82> Pito<C5><84> <kontakt@rpiton.com>
Date:   Sun Jan 1 05:01:45 2017 +0100
Python : 3.5.2
OS: GNU/Linux Debian Jessie

**problem:**
```
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    README = open(os.path.join(SETUP_DIR, 'README.rst')).read()
  File "/root/.pyenv/versions/3.5.2/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 5420: ordinal not in range(128)
```

**Comment by elcolie** [comment]
I am getting around by `pip install -r requirements.txt`

**Comment by rafalp** [comment]
Please do not use use github issues for support requests.
