### ISSUE TITLE
Online.last_click raises naive datetime warning on model's init

### ISSUE THREAD

**Issue by ioanb7** [rafalp/Misago#704]
Hi Rafal,

Here's a warning you might be interested in:

> /home/ubuntu/envs/MYMISAGOENV/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Online.last_click received a naive datetime (2017-01-26 21:41:03.392527) while time zone support is active. RuntimeWarning)             

Regards,
Ioan.

**Comment by rafalp** [comment]
That line in Misago model:

https://github.com/rafalp/Misago/blob/master/misago/users/models/user.py#L460

This is called repeately in tests suite without raising any warnings:

https://coveralls.io/builds/9863917/source?filename=misago%2Fusers%2Fmodels%2Fuser.py#L460

`timezone.now` implementation in Django:

https://github.com/django/django/blob/master/django/utils/timezone.py#L241

Looks like something's wrong with your setup. Can you please confirm that you are running with `USE_TZ = True` in your settings?

**Comment by ioanb7** [comment]
Indeed, that seems to have fixed it.
