### ISSUE TITLE
Send CSRF token in body of /api/auth/token response

### ISSUE THREAD

**Issue by armata** [rafalp/Misago#716]
Is this even possible? In addition to this or even as a replacement, it'd be nice to have Django's token authentication support.

**Comment by rafalp** [comment]
Why you can't read it from cookie?

**Comment by rafalp** [comment]
> it'd be nice to have Django's token authentication support

Can you please confirm that [token auth](http://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication) is not working at Misago?

**Comment by armata** [comment]
Closing this. django-rest-auth fits my needs perfectly :)

**Comment by rafalp** [comment]
Note: `/api/auth/token/` will be removed in next Alpha, via #719
