### ISSUE TITLE
Any way to change the favicon from the default one?

### ISSUE THREAD

**Issue by Sanjay-B** [rafalp/Misago#775]

**Comment by rafalp** [comment]
For feature or support requests as well as general feedback please use official forum instead.

Thanks!

**Comment by Sanjay-B** [comment]
Is that a yes or no? If yes, please explain how. Thanks. 

Official forum confirmation email was never sent.

**Comment by rafalp** [comment]
Hey,

Are you sure its not in spam? Looking at admin, the account was only created few minutes before you've replied here.

Anyway I've activated your account manually so you may now sign in and start your threads.

Thanks!
