### ISSUE TITLE
Weird HTML/CSS error

### ISSUE THREAD

**Issue by Sanjay-B** [rafalp/Misago#776]
If you clear your browsing history(includes cookies), you get this error even when you restart the browser.
The screen appears to be corrupted or blank. Output when F12 is pressed. 

```
Failed to load resource: the server responded with a status of 404 (Not Found)
vendor.js Failed to load resource: the server responded with a status of 404 (Not Found)
misago.js Failed to load resource: the server responded with a status of 404 (Not Found)
127.0.0.1/:182 Uncaught ReferenceError: misago is not defined
    at 127.0.0.1/:182
misago.css Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by Sanjay-B** [comment]
Another issue is with profile pictures. If you set it to default then, when you reload the page it shows a black avatar with a a green page object at the top left.

**Comment by rafalp** [comment]
Looks like you've disabled [serving static files in development](https://docs.djangoproject.com/en/1.10/howto/static-files/#serving-static-files-during-development), most likely by disabling `DEBUG` mode.

Cheers

**Comment by rafalp** [comment]
Closing this as not a bug in Misago.

**Comment by Sanjay-B** [comment]
So, how does one enable it?

**Comment by rafalp** [comment]
Please ask on official forums. Your account should now be active and possible for you to sign in. ;)

Thanks!
