### ISSUE TITLE
Showstopper on threadview using Russian locale

### ISSUE THREAD

**Issue by dariaemacs** [rafalp/Misago#793]
Hello, Rafał!
I made few categories and started new threads. But all the time I see broken page, when I click on any threads. You can test this on my server:  http://78.46.165.236/

![screenshot from 2017-04-11 07 04 47](https://cloud.githubusercontent.com/assets/22542295/24892478/98edd710-1e85-11e7-86b6-9338c71b9dfc.png)

![screenshot from 2017-04-11 07 05 16](https://cloud.githubusercontent.com/assets/22542295/24892486/a0b5249e-1e85-11e7-824c-935036754bb8.png)

**Comment by rafalp** [comment]
Hello there,

Misago's crash page is purposefully unspecific on technicalities - this is to don't leak possible vulnerabilities to people from outside of your server.

You'll need to see your error log for specifics or temporarily enable `DEBUG = True` on your site to get proper error message including stacktracke on the crash, but the latter may be security hazard in itself, as it will show part of your site's configuration to outsiders.

**Comment by dariaemacs** [comment]
Thank you!
The error is 
`'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)`

**Comment by dariaemacs** [comment]
I met this bug in my django projects. Usually it is in the model.py or view.py. 
But I don't know where is it in Misago.

**Comment by rafalp** [comment]
Looks like you've just found feature that fails to handle unicode strings.

Please provide the stacktrace and I'll release the fix.

**Comment by dariaemacs** [comment]
`Exception Location: ...rest_framework/fields.py in to_representation, line 762`

**Comment by rafalp** [comment]
I'll need entire stacktrace to debug this effectively.

**Comment by dariaemacs** [comment]
http://dpaste.com/3QSAKKD

You mean this?

**Comment by rafalp** [comment]
Yup, much better. Thanks!

**Comment by rafalp** [comment]
I can't reproduce the error. Can you use "local vars" on django's debug view to see what is inside the "value" that goes to `return six.text_type(value)`? I'm wondering if it may be some object defining `__str__` but actually returning unicode.

**Comment by rafalp** [comment]
I've noticed that there are parts of codebase that use non-unicode gettext functions instead of their u- prefixed versions that work for unicodes (eg. `gettext` instead of `ugettext`).

I'm guessing that `gettext("Threads")` tries to translate itself to string that contains non-ascii signs, and blows on thread's path serialization.

I've just pushed the change to master. Could you please pull it locally and see if it fixes the issue?

**Comment by dariaemacs** [comment]
I use ugettext_lazy in settings.py:
`from django.utils.translation import ugettext_lazy as _`

**Comment by rafalp** [comment]
Can you please confirm that running latest code from master fixes the issue?

**Comment by dariaemacs** [comment]
Ok. I will try. I have to download new version from master and run. Is it right?

**Comment by rafalp** [comment]
Aye.

**Comment by dariaemacs** [comment]
Sorry, I'm little bit confused. 
I installed Misago by the help pip command in my virtualenv. And I have no idea, how can I update my version misago. 
Maybe I have to activate virtual env, delete old Misago then do git clone and install master.

**Comment by rafalp** [comment]
Allright, then can you please send current version of russian translation for me to test my changes ?

**Comment by dariaemacs** [comment]
I'm guessing that it's because of Russian themes and contents of them. You can copy Russian word to new theme and content of it.
Russian translation isn't reason of showstopper.

**Comment by dariaemacs** [comment]
Thread: Инфраструктура
Theme: водоснабжение
Content: здесь будем обсуждать водоснабжение

**Comment by rafalp** [comment]
Please let me try with Russian translation.

**Comment by dariaemacs** [comment]
You have it. I didn't add new words, but if you want to get files...



[foo.zip](https://github.com/rafalp/Misago/files/917438/foo.zip)

**Comment by rafalp** [comment]
Thanks,

Here's my dev instance of Misago running russian translation, one comming behind master:

<img width="1439" alt="zrzut ekranu 2017-04-12 o 20 15 12" src="https://cloud.githubusercontent.com/assets/750553/24972862/1e570678-1fbd-11e7-8afe-66dfacf86229.png">

Here's same instance running latest master, that replaces all `gettext` with `ugettext`:

<img width="1440" alt="zrzut ekranu 2017-04-12 o 20 15 55" src="https://cloud.githubusercontent.com/assets/750553/24972875/2de8db98-1fbd-11e7-962a-d48e18a531b0.png">

So its fixed, with fix landing in next alpha. 🎉

Stay tuned, I'll be releasing in ~half hour.

**Comment by dariaemacs** [comment]
Ok, thank you very much! It's for you :1st_place_medal: ! 
I hope I will see the beautiful page like you :) tomorrow.

**Comment by rafalp** [comment]
@dariaemacs Alpha 9 containing the fix for this issue has been released. Have fun and keep up the good work with your translation effort!

**Comment by dariaemacs** [comment]
I've tested! This bug disappeared!:)
Thanks, Rafał!
