### ISSUE TITLE
Typo in django.po

### ISSUE THREAD

**Issue by dariaemacs** [rafalp/Misago#795]
Hello there! I don't know where can I tell about this little typo in English locale.
form **V**elow, instead **b**elow
This is 1775 string in the file django.po

```
#: templates/misago/emails/register/inactive.txt:30
msgid ""
"Once your account is activated, you can always sign in to it using the form "
"velow:"
msgstr ""
```

**Comment by dariaemacs** [comment]
djangojs.po:272 
Is't ok? 

Bo**l**der? Maybe is it Bo**r**der?

```
#: static/misago/js/misago.js:2
msgid "Bolder selection"
```

**Comment by rafalp** [comment]
`Bolder selection` is help text for "bold" button in editor.

"redeem" as in become available again, but I admit that may be engrish and not really correct.

**Comment by dariaemacs** [comment]
Ok, thank you :). Can you answer the question on the Misago forum: https://misago-project.org/t/the-content-of-the-warning-message/346/

**Comment by rafalp** [comment]
Hey, I still didn't fix original typo.

**Comment by dariaemacs** [comment]
Oh, I'm sorry :).
