### ISSUE TITLE
Don't see users list

### ISSUE THREAD

**Issue by dariaemacs** [rafalp/Misago#824]
Hello there!

My user posted message day ago. But I don't see him in the users list. 
Please, tell me why?

![screenshot from 2017-04-26 20 39 22](https://cloud.githubusercontent.com/assets/22542295/25448547/75d4db1e-2ac1-11e7-9487-32c4fef132dd.png)

My settings and users have the same settings (Can see users list):
![screenshot from 2017-04-26 20 39 53](https://cloud.githubusercontent.com/assets/22542295/25448553/7d01804a-2ac1-11e7-9d96-b3941ee8b6fd.png)

New post:
![screenshot from 2017-04-26 20 40 31](https://cloud.githubusercontent.com/assets/22542295/25448561/85d18c1a-2ac1-11e7-8a05-0a9a5df1797a.png)

**Comment by rafalp** [comment]
Hey, this isn't a bug, so its not suitable for Github. Please ask this question on our support forums instead and I'll happily explain whats happening. ;)

**Comment by dariaemacs** [comment]
Sorry). I've posted this message in the forum. :)
