### ISSUE TITLE
Does MIsago support Chinese search?

### ISSUE THREAD

**Issue by promanz** [rafalp/Misago#849]
up:
Does MIsago support Chinese search?

**Comment by rafalp** [comment]
Please refer to [official forums](https://misago-project.org/) to ask questions regarding translations as per readme. Issue tracker is only for reporting bugs.

**Comment by rafalp** [comment]
Welp, dunno where I've got the translation idea from.

Misago uses Django's postgresql fulltext search facilities under the hood, so the question would best be asked on django users mailing group IMHO.

If there are any issues, I'm open for pull requests improving it.

**Comment by promanz** [comment]
thank you, i thank the problem might be URLencode and RE:

rl(r'^search/(?P<search_provider>[-a-zA-Z0-9]+)/$', api.search, name='search'),

**Comment by rafalp** [comment]
No. This is search provider name, not search query.

**Comment by promanz** [comment]
oh...

**Comment by promanz** [comment]
I've configured the misago Chinese search by installing zhparser, oh yeah!
