### ISSUE TITLE
User defined Question/Answers CAPTCHA not working.

### ISSUE THREAD

**Issue by cRyckreator** [rafalp/Misago#871]
New user can register successfully with a random answer.
It's an easypicking bug inside the misago/users/api/userendpoints/create.py from line#27 to line#33
Just move the CAPTCHA validation before returning any response.

BTW, It's quite amazing you've done most of the developing by yourself.Would you like a hand with this project?I'm familiar with Django and React.js, and it'll be my honor to become a contributor.

**Comment by rafalp** [comment]
Code in question: https://github.com/rafalp/Misago/blob/master/misago/users/captcha.py#L27

But I can't see anything wrong here. Looking at [test coverage](https://coveralls.io/builds/11923448/source?filename=misago%2Fusers%2Fcaptcha.py#L27) it looks like there's none for this captcha implementation. That could've been fixed via implementing test that tries to register user account while forum is configured to use Q&A captcha.

> Would you like a hand with this project?I'm familiar with Django and React.js, and it'll be my honor to become a contributor.

Hey, thanks.

Keep on mind however that contributor status  is not something given, but something earned. I've seen a lot of people who didn't understand that who showed up, were active for few weeks working on single PR only to go silent as their PR's were nearing completion and they had to implement feedbacks or even invest greater amount of effort to wrap up their submissions. Speaking from experience this is probably correlated with those people lack of personal stakes in Misago. They don't run forum on Misago, they don't feel personal interest to bugfix or improve it. So they quickly get bored and move on.

With above in mind probably best contributor material for Misago are people who are invested into it (running site on Misago) that wish to help themselves by submitting the fixes and improvements upstream.

Still, if you wish to carry on, PR that fixes this bug and adds test that asserts that Q&A captcha's answer is validated by API endpoint that registers new user account.

**Comment by rafalp** [comment]
The bug was actually quite larger than what you've reported. In nutshell, API included interrupt after form data was invalid, but it didn't include other one that would step in if captcha also was invalid.

I've added tests that checked this too
