### ISSUE TITLE
 email conf  in `settings.py` and reply 500 error.

### ISSUE THREAD

**Issue by dofine** [rafalp/Misago#895]
Hi, maybe this should be posted at misago-project.org. But clicking registration button takes forever and couldn't load, because google.com is blocked in China, so recaptcha is unavailable.

1. In my own test site,  user registration is configured to be No activation required, because email system is not set in the `settings.py` and I don't want to send emails for now. Registration alerts with something wrong in the banner popup, while users can actually login with their username/password. Is this due to wrong email client and server setting? 

2. One more strange thing is, users can only reply to threads of their own. Reply to others' threads would get a 500 internal server error. Don't know why.

Thanks a lot!

**Comment by rafalp** [comment]
Hey,

> because email system is not set in the settings.py and I don't want to send emails for now

Valid email setup is hard requirement in Misago, and no setup at all means implicit SMTP with no authentication, which in majority of cases will fail with authentication error on attempt to send e-mail.

Emails are sent out quite a lot by Misago:

- When user registers, he receives welcome email
- When user replies thread subscribed to by others, they'll receive an email with notification
- When user changes sign-in credentials, he receives confirmation e-mail
- When user forgets his sign in credentials, he receives confirmation e-mail

If you really don't mind, you may explictly disable emails via changing your e-mail backend to dummy one, as documented in [Django docs](https://docs.djangoproject.com/en/1.11/topics/email/#dummy-backend), but Misago will take no notice of this and will assume that mails are going out to the users, even if they'll vanish in it.

**Comment by dofine** [comment]
Thanks for your reply!
  > When user replies thread subscribed to by others, they'll receive an email with notification
Can I turn this off or change its default value to be no? Didn't find relevant docs.
Per user setting can be turn off in user profile settings option.
I'd like this default to be turned off, because I'm still playing with Misago now.

**Comment by rafalp** [comment]
You can change it in admin control panel to default to no subscription, but that will only work for newly registered accounts.

**Comment by dofine** [comment]
Got it. Great work :beers:

**Comment by dofine** [comment]
Hi @rafalp , finally I registered on the forum. And it's very nice of you if you would help me with this question:

https://misago-project.org/t/how-to-edit-categories-without-admin-rights-and-two-other-questions/436/
