### ISSUE TITLE
python2 syntax used in call to print in extras

### ISSUE THREAD

**Issue by livegraph** [rafalp/Misago#905]
hi,
some modules in "extras" package still uses py2 syntax, please check details below:

```
\extras\fixabsoluteimports.py", line 41
    print file_path
                  ^
SyntaxError: Missing parentheses in call to 'print'

\extras\fixrelativeimports.py", line 17
    print '====' * 8
               ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by rafalp** [comment]
Hey!

The extras package is purely set of private tools that I'm committing to make sure I'll wont lose them when they are needed next time. There's no support for those nor goal for them to work on py3k. As long as they run when I need them, I'm happy ;) If sometime down the line I'll need to run them on py3k, I'll fix them then.

Closing this as wontfix, but thank you for vigilance!
