### ISSUE TITLE
Email reject issue due to invalid HELO (not FQDN)

### ISSUE THREAD

**Issue by Oldzhay** [rafalp/Misago#918]
Hello,
I've tried to register to https://misago-project.org/ and it worked, but confirmation/activation link never came to my inbox.

Checking my email logs I see the following message:
`
Sep 22 11:00:08 mail postfix/smtpd[31011]: NOQUEUE: reject: RCPT from unknown[138.68.79.200]: 504 5.5.2 <misago-20170107>: Helo command rejected: need fully-qualified hostname; from=<noreply@misago-project.org> to=<e@mail> proto=ESMTP helo=<misago-20170107>
`

It says that you must format your email headers putting an FQDN to your helo as `misago-20170107` is not a valid one. It should be something like: misago-project.org or mail.misago-project.org, mta.misago-project.org whatever you want, but it must be fully cualified domain name (FQDN)

It is a good idea when email travels the Internet authenticated (FPS, DKIM, well formatted headers, etc).

**Comment by rafalp** [comment]
Hey,

This isn't Misago issue, and thats what this issue tracker is for. Still, thanks for letting me know.

**Comment by Oldzhay** [comment]
Ok, I thrust you, but how people activate their accounts at first place? And who is generating the email message? It is the misago code, isn't it? Someone puts `misago-20170107 ` as HELO header

**Comment by rafalp** [comment]
> Ok, I thrust you, but how people activate their accounts at first place?

Email spam filters are annoyingly gray area - I'm having plenty of new user registrations at project's forums, and extreme majority of those pass e-mail activation.

>  It is the misago code, isn't it?

No, assuming that all email's headers are set by the application is incorrect. ;)

For example, the hostnames are something that depends on how the host and DNS records are setup. Hence closing this issue as something about our server, not the Misago as python/js solution.

I've activated your account manually. ;)

Thanks!

**Comment by rafalp** [comment]
I've looked it up and indeed my `/etc/hosts` had typo in that messed up the FQDN resolution.

Thanks again!
