### ISSUE TITLE
DEBUG = False causes server error (500)

### ISSUE THREAD

**Issue by AustenLamacraft** [rafalp/Misago#919]
Great project! Really hoping to use this in production for a class I'm teaching in a couple of weeks.

I have a problem with setting DEBUG = False, which gives a 500 error, even with ALLOWED_HOSTS  set to '*' or '127.0.0.1'. 

I'm using python 3.4.3 and Django 1.11.5. The error log is attached.

Any ideas would be wonderful!

Austen

[mysite.log](https://github.com/rafalp/Misago/files/1326912/mysite.log)

**Comment by rafalp** [comment]
Hey!

Please do not use our bugtracker for support requests. We have [project forums](https://misago-project.org/) for that ;)

If you can't start thread there for technical reasons, let me know and I'll help you out with overcoming those.
