### ISSUE TITLE
Application labels aren't unique, duplicates: search

### ISSUE THREAD

**Issue by versionzhang** [rafalp/Misago#922]
Hello，
 
I use misago and django-oscar together.
I got this error.

https://docs.djangoproject.com/en/1.11/ref/applications/#for-application-authors

I check django docs and get some solutions.

**Comment by rafalp** [comment]
Hey,

Do you have any new updates on this?

Personally, I'm not that convinced that Misago should really step out the way here, seeing how "search" is supergeneric name for app.

**Comment by rafalp** [comment]
This is actually valid report as I've noticed that all other apps in Misago define `apps.py` configs with custom labels containing `misago_` prefix.

Hey, @versionzhang PR for this is welcome! 😚
