### ISSUE TITLE
Thread reply form autofocusing

### ISSUE THREAD

**Issue by shtuffit** [rafalp/Misago#928]
What would be the best way to autofocus on the reply field for a thread? Ideally with a newline or 2 after any quoted text.

**Comment by rafalp** [comment]
Hey shtuffit, thank you for taking interest in Misago!

You should propably look at customizing the [componentDidMount](https://github.com/rafalp/Misago/blob/master/frontend/src/components/editor/index.js#L30) method that's called after reply editor's textarea gets initialized.
