### ISSUE TITLE
an install error 

### ISSUE THREAD

**Issue by sasimi19** [rafalp/Misago#937]
I have an error below
I don't know how to fix it. plz help me~
thanks in advance

(myvenv) C:\xampp\htdocs\misago_project>pip install misago
Collecting misago
  Using cached Misago-0.13.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-nj49eq6r\misago\setup
.py", line 11, in <module>
        README = open(os.path.join(SETUP_DIR, 'README.rst')).read()
    UnicodeDecodeError: 'cp949' codec can't decode byte 0xf0 in position 714: il
legal multibyte sequence

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\ADMINI~1
\AppData\Local\Temp\pip-build-nj49eq6r\misago\

**Comment by rafalp** [comment]
Hello,

Please ask on our [forums](https://misago-project.org) as per readme:

> For feature or **support requests** as well as general feedback please use official forum instead.
