### ISSUE TITLE
404 Error with fontawesome-webfont.ttf

### ISSUE THREAD

**Issue by fxt0706** [rafalp/Misago#938]
Hi, rafalp

After I configured my site and login the admincp, all the icons displayed are empty boxes.

In the Chrome console, I got 

```
fontawesome-webfont.woff Failed to load resource: the server responded with a status of 404 (Not Found)
fontawesome-webfont.ttf Failed to load resource: the server responded with a status of 404 (Not Found)
Slow network is detected. Fallback font will be used while loading: http://gzgit.xyz/static/misago/admin/fonts/glyphicons-halflings-regular.woff
```

In the python console, I got 
`[27/Oct/2017 07:03:15] "GET /static/misago/admin/fonts/fontawesome-webfont.woff?v=4.2.0 HTTP/1.0" 404 10414
[27/Oct/2017 07:03:16] "GET /static/misago/admin/fonts/fontawesome-webfont.ttf?v=4.2.0 HTTP/1.0" 404 10414
`

I searched many posts about fontawesome but still can't fix it. Please help me if you know how to do with it.

Thank you

**Comment by rafalp** [comment]
Hello!

As per our readme, issue tracker is here for tracking actual bugs within software. For support in setting up your site, please ask on [our forums](https://misago-project.org).

Thanks!
