### ISSUE TITLE
License adjustment

### ISSUE THREAD

**Issue by Karmak23** [rafalp/Misago#958]
Hello @rafalp !
Thanks for this awesome piece of software. I'm still discovering what you put in it, I'm impressed.

I'd like to bring to your attention that the GNU GPL v2 doesn't protect users of remote services (eg. web applications running on distant servers).

In order to protect users and the web app software to remain free as in free speech, you should use the GNU Affero GPL version 3.

Affero proposed the necessary adaptations to the GNU GPL for web applications, and that's why this licence exists.

https://en.wikipedia.org/wiki/GNU_Affero_General_Public_License

regards,

**Comment by rafalp** [comment]
Hey Karmak, thanks for taking moment to raise the issue.

This is first time I'm hearing about Affero GPLv3. Could you please tell me what it really protects users from?

**Comment by Karmak23** [comment]
In short, the GPLv2 only covers binary applications running localy on the user's computer.

When the user uses a distant web application on a remote server, the GPLv2 does NOT ensure the user can get the source of the app.

Thus, covering web apps with GPLv2 has been historically (in the late 90's and early 2k's) a way for cheater companies to say "hey, I do free software", then closing their app because the GPLv2 doesn't force them to offer back the source, *in case of a web app*.

If someone takes misago, modifies it in a cool way, neither you nor me will be able to get the modifications, because it's not covered by affero gplv3…

License HELL.

Diaspora, Flask, MediaGoblin, Launchpad, ownClound are all under AGPLv3.

Any PHP/Python/Ruby/JS webapp that is under the GPLv2/3 (not the “A”) is a terrible mistake.

Hope I'm clear.

« The Free Software Foundation has recommended that the GNU AGPLv3 be considered for any software that will commonly be run over a network. » (wikipedia page)

**Comment by rafalp** [comment]
Thank you for explaining. 

> If someone takes misago, modifies it in a cool way, neither you nor me will be able to get the modifications, because it's not covered by affero gplv3…

Yeah, I don't want to place that requirement on people building upon Misago. You've made your forum look cool? Its up to you to share it with community, or maintain its exclusivity to yourself. And lets not get started about making companies release customizations or integrations with propertiary services or assets.

If I was to relicense Misago (and I'm considering that), I would relicense it to MIT or BSD.

Still, thank you for taking time to let me know about your concerns.
