### ISSUE TITLE
Cannot change the subject of my own posts (UTF8 issue / configuration problem ?)

### ISSUE THREAD

**Issue by Karmak23** [rafalp/Misago#959]
When I make a post in a new subject, I can edit the body of the post without problem, but I cannot change the subject line.

If I edit it then save, I get a notification message "an unknown error occured", and nothing more happens.

This happens even if I'm an administrator trying to update a subject. Owner / original poster also cannot modify it.

browser console says :

```
PATCH https://enfants-et-parents.net/api/threads/10/ 500 (Internal Server Error)
send @ vendor.js? [sm]:13143
ajax @ vendor.js? [sm]:12624
(anonymous) @ misago.js? [sm]:40837
value @ misago.js? [sm]:40796
value @ misago.js? [sm]:40952
value @ misago.js? [sm]:24445
n.handleSubmit @ misago.js? [sm]:5169
r @ vendor.js? [sm]:22917
a @ vendor.js? [sm]:17001
s @ vendor.js? [sm]:17024
p @ vendor.js? [sm]:16426
m @ vendor.js? [sm]:16437
r @ vendor.js? [sm]:28327
processEventQueue @ vendor.js? [sm]:16640
r @ vendor.js? [sm]:22985
handleTopLevel @ vendor.js? [sm]:22996
i @ vendor.js? [sm]:23073
perform @ vendor.js? [sm]:27628
batchedUpdates @ vendor.js? [sm]:22749
i @ vendor.js? [sm]:25756
dispatchEvent @ vendor.js? [sm]:23148
```

Server side in debug mode, it says :

```
psycopg2.DataError: unsupported Unicode escape sequence
LINE 1: ...alse, false, false, false, true, 'changed_title', '{"old_tit...
                                                             ^
DETAIL:  Unicode escape values cannot be used for code point values above 007F when the server encoding is not UTF8.
CONTEXT:  JSON data, line 1: {"old_title":...
```

Note: I can post a subject with utf8 characters (like « or ⋅ or …). Only the update via `PATCH` fails.

I can remember that I can also modify a subject which does NOT contain UTF8, because I already updated a title `la "boite à jouets"` to `la « boîte à jouets »` (with non-breaking spaces and utf8 «) without any problem.

It does not seem a database UTF-8 encoding problem, because I already have plenty UTF8 chars in it. This does not seem to be an error at the nginx proxy level (I use nginx + latest gunicorn, postgresql 9.5, python 3.5.1 on ubuntu 16.04), because other UTF8 post succeed since I've installed misago.

Did you ever encounter this problem ? Any advice on where / how to pinpoint it ?

Perhaps this would just lead to a change in the installation documentation to ensure everything is UTF-8, when we get the final cause of the issue. But My current research leads me to something weird in the client `PATCH` code, or at the DRF level.

regards,

**Comment by rafalp** [comment]
I've never experienced anything like that.

Could you please try reproducing this error on project forums, posting your thread in testing category and then editing its title to whatever is causing and problem? If error occurs there, it'll get logged to sentry with necessary info for me to debug it further.

**Comment by Karmak23** [comment]
I had no problem with https://misago-project.org/t/testing-959-issue-with-a-medium-dot/530/ I could edit the subject without any issue.

Where could a configuration problem come from ?

**Comment by Karmak23** [comment]
BTW, sorry, I didn't post in the testing category.

**Comment by Karmak23** [comment]
Regarding https://github.com/cakephp/cakephp/pull/9708, it seems my postgresql database could be NOT in UTF8, which seems crazy, but I will check.

**Comment by Karmak23** [comment]
OK, that was that.
For an obscure reason, `template1` is in `SQL_ASCII` on my brand new server…

```
createdb -E utf8 misago8 -O misago
createdb: database creation failed: ERROR:  new encoding (UTF8) is incompatible with the encoding of the template database (SQL_ASCII)
HINT:  Use the same encoding as in the template database, or use template0 as template.
```

I used https://stackoverflow.com/questions/8806631/how-to-convert-a-db-in-postgresql-to-utf8#8809872 to migrate the database, and the problem vanished.

Sorry for the noise.
