### ISSUE TITLE
User permission "see category" generates 404 but should generate 403

### ISSUE THREAD

**Issue by Karmak23** [rafalp/Misago#963]
On [my misago instance](https://enfants-et-parents.net/), I configured `guests` with `See Only`  permissions on some categories, to be able to see these categories, but not their contents. This is done to make unregistered users get a glance of the website, without reading threads which are very private and must stay confidential.

On the "categories" page, the category name is clickable, and generates a 404 ([example](https://enfants-et-parents.net/c/parentage-bienveillant-et-inclusif/3/)) when clicked, for `guests`.

I think the 404 message is misleading (broken link, page deleted/moved) and gives a bad image of the website.

I'm questionning :

- should the link on the category be generated, given the fact that the user has no permission to see the contents ? No link on such category names seems fine to me. 

- whatever the answer to previous question, I think that a 403 is more appropriate. The 403 message would be "you have no permission to view this content", leading probably to a full message like "you have no permission to view this content. Please log in or register to display it."  Members and guests would better understand why the page is not viewable, and this could reinsurre them that the forum is really private.

Any thoughts ?

**Comment by rafalp** [comment]
Can you please post the screenshot of category's visibility permissions for guest? What you are saying looks like a bug, but I need to know perms to say where and what to do with it ;)

Thanks!

**Comment by Karmak23** [comment]
(Sorry, can't attach images, github says "something went really wrong…") 

Permissions for `See only` (« Voir uniquement » in french) :

https://mercibien.net/fichiers/screenshots/misago/capture1.png

(= can see category and cannot see its contents)

Permissions for `Guest` (« Invité » in french) on tested category :

https://mercibien.net/fichiers/screenshots/misago/capture2.png

Category listing :

https://enfants-et-parents.net/categories/

404 on the category :

https://enfants-et-parents.net/c/parentage-bienveillant-et-inclusif/3/

**Comment by rafalp** [comment]
Can see category but can't see its contents is a bug. Should be 403 here because pretending that category doesn't exist is pointless if we can see it on threads list.

**Comment by Karmak23** [comment]
Yep, exactly !

**Comment by rafalp** [comment]
Closing as fixed in next release.
