### ISSUE TITLE
website blocked by eset

### ISSUE THREAD

**Issue by danielmroberts** [rafalp/Misago#977]
Just wanted to give the project a heads up that ESET is blocking your site. I don't know if it is just a false positive or not. https://imgur.com/a/befbk

**Comment by rafalp** [comment]
This is ESET guys having smart idea to block a lot of DigitalOcean's IPs because some of them were used to host some shady stuff by bad people. Eh, may as well send them an e-mail requesting de-listing. Thanks.

**Comment by rafalp** [comment]
I've been informed by ESET that my website will be delisted in next update.

Thank you for reporting, @danielmroberts !
