### ISSUE TITLE
Injecting default category data

### ISSUE THREAD

**Issue by einarf** [rafalp/Misago#978]
(This is not a major problem for me atm, but I thought an issue on this could be helpful)

Just a minor observation that caused a lot of confusion and digging:

I'm spinning up containers with Misago running were I inject default data such as categories from json files or other data if needed. This would normally have been dumped from another misago database. The categories rendered correctly on the main categories page, but they did not appear in other locations also causing the "All, Mine, New, Unread" tabs to be completely empty.

I figured out that categories actually use a nested set model with left and right values, so those will not be calculated correctly unless created though the rest api endpoint.

Would it make sense to create a management command to mend injected data?

**Comment by einarf** [comment]
This is mainly an issue when you automate things during development and testing. I needed a fairly static setup with categories, ranks, permissions and acls and setting this up every time was a bad deal.

**Comment by rafalp** [comment]
Hey Einarf!

Misago uses the [MPTT](https://github.com/django-mptt/django-mptt/) for storing categories tree. Categories manager has method for rebuilding tree that may be called from `python manage.py shell`:

```python
from misago.categories.models import Category
Category.objects. rebuild()
```

Would this help? If not, including the `fixcategoriestree` command is not something I am against. It would be useful for this very case.

**Comment by rafalp** [comment]
Thinking about this now, imho the easiest way about it would be to create custom app with data migrations doing what you want.

The MPTT algo doesn't work inside the migrations, because models in those are just placeholder models for Django's ORM to know what fields are there to query, but its simple enough to fix those manually in the migration's code.
