### ISSUE TITLE
Thread view contains empty moderation menu

### ISSUE THREAD

**Issue by ReyKoxha** [rafalp/Misago#982]
![unbenannt](https://user-images.githubusercontent.com/13523850/38138481-89bd3602-342b-11e8-83e3-5cca01cb0b67.PNG)
See the screenshot above. I am unable to close topics or make them sticky.

On user pages the options appear though.

**Comment by rafalp** [comment]
@ReyKoxha I'll require more data to reproduce this. Could you open your browser's console, do:

```
misago._context.THREAD.acl
```

And then paste here its output?

I'm interested in this:

<img width="873" alt="zrzut ekranu 2018-04-01 o 01 29 50" src="https://user-images.githubusercontent.com/750553/38168446-37d4f5ec-354c-11e8-97c7-e86b3b528da3.png">

**Comment by ReyKoxha** [comment]
Fixed, I messed up with permissions.

I am very sorry for the inconvenience, sorry for my incompetence.

**Comment by rafalp** [comment]
@ReyKoxha this is still a bug. This menu should never appear empty.

**Comment by rafalp** [comment]
This issue is caused by interface checking if user may unhide the thread without first checking if thread is actually hidden.
