### ISSUE TITLE
Can Misago build in mongodb ?

### ISSUE THREAD

**Issue by WeirdWired** [rafalp/Misago#987]
Hello guys i just wondering

i just wanna make forum with misago and mongoDB

can you help me for config database with mongoDB

Sorry for my english native, and im new in django framework.

thanks.

**Comment by rafalp** [comment]
Hello WeirdWired!

Misago is developed for PostgreSQL and doesn't work with any other database.

**Comment by WeirdWired** [comment]
oh is so sad fact okay , maybe i can make it one 

thanks anyway.
