### ISSUE TITLE
Misago without Docker

### ISSUE THREAD

**Issue by fdik** [rafalp/Misago#991]
Hi,

is there a way to install Misago without Docker, i.e. using virtualenv?

Yours,
VB.

**Comment by rafalp** [comment]
Hi!

Misago doesn't require Docker for setup. Could you please tell me where did you read that it does?

Thank you!

**Comment by einarf** [comment]
Do you mean a prod setup or local dev setup?

**Comment by fdik** [comment]
Saw it, my mistake. Thank you for the hint. It was this sentence misleading me:

“To start Misago site locally, first make sure you have Docker installed.”

**Comment by rafalp** [comment]
Yeah, we don't require Docker, but its easiest way to setup Misago on your machine to try it out yourself.

**Comment by kahurani** [comment]
while i respect your opinion, this, however, doesn't change the fact that not all developer/misago users want to use docker which means adding information/code/instructions on how you can run misago without docker could be good.

**Comment by einarf** [comment]
If Misago had a company behind it with paying customers I would agree with @kahurani. Misago is not that. It's a community project were people spend their hard earned free time to make things happen. If you have an alternative solution for the standard dev setup you can always make a repo with a guide sharing with others. If this gets popular it could eventually be part of the project docs. Opensource is both give and take.
